import PaymentsLayout from '@/layouts/PaymentsLayout';
import { Head, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';
import { useState } from 'react';

type Account = { id: number; name: string; code: string; type: string; status: string; currency_code: string; notes: string | null };
type Props = { accounts: Account[]; currencyCode: string; can: { create: boolean; update: boolean } };
const types = [['cash', 'Cash'], ['bank', 'Bank'], ['card_clearing', 'Card clearing'], ['cheque_clearing', 'Cheque clearing'], ['other', 'Other']];

function AccountForm({ account, currencyCode, close }: { account?: Account; currencyCode: string; close: () => void }) {
    const form = useForm({ name: account?.name ?? '', code: account?.code ?? '', type: account?.type ?? 'cash', status: account?.status ?? 'active', currency_code: account?.currency_code ?? currencyCode, notes: account?.notes ?? '' });
    const submit = (event: FormEvent) => { event.preventDefault(); const options = { preserveScroll: true, onSuccess: close }; account ? form.patch(`/financial-accounts/${account.id}`, options) : form.post('/financial-accounts', options); };
    return <form onSubmit={submit} className="space-y-3 rounded-lg border bg-white p-5"><h3 className="font-semibold">{account ? `Edit ${account.name}` : 'Create financial account'}</h3><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Name<input required maxLength={255} value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" />{form.errors.name && <span className="text-red-600">{form.errors.name}</span>}</label><label className="text-sm">Code<input required maxLength={64} value={form.data.code} onChange={(e) => form.setData('code', e.target.value.toUpperCase())} className="mt-1 w-full rounded border px-3 py-2" />{form.errors.code && <span className="text-red-600">{form.errors.code}</span>}</label><label className="text-sm">Type<select value={form.data.type} onChange={(e) => form.setData('type', e.target.value)} className="mt-1 w-full rounded border px-3 py-2">{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm">Status<select value={form.data.status} onChange={(e) => form.setData('status', e.target.value)} className="mt-1 w-full rounded border px-3 py-2"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="text-sm">Currency<input required maxLength={3} value={form.data.currency_code} onChange={(e) => form.setData('currency_code', e.target.value.toUpperCase())} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm md:col-span-2">Notes<textarea maxLength={5000} value={form.data.notes} onChange={(e) => form.setData('notes', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label></div><div className="flex gap-2"><button disabled={form.processing} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50">Save account</button><button type="button" onClick={close} className="rounded border px-4 py-2">Cancel</button></div></form>;
}

export default function FinancialAccounts({ accounts, currencyCode, can }: Props) {
    const [editing, setEditing] = useState<number | 'new' | null>(null);
    return <PaymentsLayout><Head title="Financial Accounts" /><div className="mb-5 flex items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Financial accounts</h2><p className="text-sm text-slate-500">Organization-level destinations used when posting payments.</p></div>{can.create && editing !== 'new' && <button onClick={() => setEditing('new')} className="rounded bg-slate-900 px-4 py-2 text-white">Create account</button>}</div>
        {editing === 'new' && <div className="mb-6"><AccountForm currencyCode={currencyCode} close={() => setEditing(null)} /></div>}
        <div className="overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Code</th><th className="p-3">Name</th><th className="p-3">Type</th><th className="p-3">Currency</th><th className="p-3">Status</th><th className="p-3"></th></tr></thead><tbody>{accounts.map((account) => <tr key={account.id} className="border-t"><td className="p-3 font-medium">{account.code}</td><td className="p-3">{account.name}</td><td className="p-3 capitalize">{account.type.replaceAll('_', ' ')}</td><td className="p-3">{account.currency_code}</td><td className="p-3 capitalize">{account.status}</td><td className="p-3 text-right">{can.update && <button onClick={() => setEditing(editing === account.id ? null : account.id)} className="rounded border px-3 py-1">Edit</button>}</td></tr>)}</tbody></table></div>
        {typeof editing === 'number' && <div className="mt-6"><AccountForm account={accounts.find((account) => account.id === editing)} currencyCode={currencyCode} close={() => setEditing(null)} /></div>}
    </PaymentsLayout>;
}
