import { Button, ButtonLink } from '@/components/ui/Button';
import ApplicationShell from '@/layouts/ApplicationShell';
import { Head, useForm } from '@inertiajs/react';
import type { FormEvent, ReactNode } from 'react';
import { useEffect, useMemo, useRef, useState } from 'react';

type Thickness = 'fine' | 'normal' | 'thick';
type BorderWidth = '0pt' | '.45pt' | '.7pt' | '.85pt' | '.95pt' | '1.1pt' | '1.4pt';
type Alignment = 'left' | 'center' | 'right';
type TypographyStyle = { visible: boolean; font_family: 'DejaVu Sans' | 'Helvetica'; font_size: number; font_weight: number; color: string; letter_spacing_em: number; line_height: number; alignment: Alignment; margin_top_mm: number; margin_bottom_mm: number };
type TextGroup = { font_family: 'DejaVu Sans' | 'Helvetica'; font_size: number; font_weight: number; color: string; line_height: number; alignment: Alignment; width_percent?: number; wrap?: boolean };
type BoxStyle = { visible: boolean; font_size: number; line_height: number; label_color: string; value_color: string; label_weight: number; value_weight: number; alignment: Alignment; padding_mm: number; margin_top_mm: number; margin_bottom_mm: number; border_color: string; border_width: BorderWidth; background_color: string; width_percent: number; row_spacing_mm: number; label_gap_mm: number; labels: TextGroup; values: TextGroup };
type PdfTemplate = {
    page: { base_font_size: number; text_color: string; line_height: number; margin_top_mm: number; margin_right_mm: number; margin_bottom_mm: number; margin_left_mm: number };
    brand: { accent_color: string };
    logo: { visible: boolean; max_width_mm: number; max_height_mm: number; margin_bottom_mm: number; alignment: Alignment; preserve_aspect_ratio: boolean };
    company_name: TypographyStyle & { position: 'above_logo' | 'below_logo' | 'beside_logo'; logo_spacing_mm: number; width_percent: number; margin_left_mm: number; margin_right_mm: number; horizontal_offset_mm: number; text_transform: 'none' | 'uppercase' };
    company_block: BoxStyle & { show_address: boolean; show_tax_identifier: boolean; show_phone: boolean; show_email: boolean; show_registration_number: boolean; show_patente_number: boolean; show_additional_identifiers: boolean };
    recipient_block: BoxStyle & { title_size: number; name_size: number; contact_size: number; title_weight: number; name_weight: number; name_color: string; heading_spacing_mm: number; heading: TextGroup; name: TextGroup; contact: TextGroup; show_address: boolean; show_phone: boolean; show_email: boolean; show_tax_identifier: boolean };
    document_title: TypographyStyle & { margin_left_mm: number; margin_right_mm: number; width_percent: number; text_transform: 'none' | 'uppercase' };
    document_info: { visible: boolean; label_font_size: number; value_font_size: number; label_font_family: 'DejaVu Sans' | 'Helvetica'; value_font_family: 'DejaVu Sans' | 'Helvetica'; label_weight: number; value_weight: number; label_color: string; value_color: string; header_background: string; value_background: string; border_color: string; border_width: BorderWidth; padding_y: number; padding_x: number; margin_bottom_mm: number; column_1_width: number; column_2_width: number; column_3_width: number; column_4_width: number; width_percent: number; row_height_mm: number; margin_top_mm: number; outer_border: boolean; inner_horizontal_borders: boolean; inner_vertical_borders: boolean; border_opacity: number; border_style: 'solid' | 'dashed' | 'dotted'; label_alignment: Alignment; value_alignment: Alignment };
    item_table: { header_background: string; header_text: string; header_font_size: number; header_font_weight: number; body_font_size: number; body_text_color: string; body_font_weight: number; separator_color: string; separator_opacity: number; separator_thickness: Thickness; separator_style: 'solid' | 'dashed' | 'dotted'; grid_mode: 'horizontal' | 'full' | 'none'; padding_y: number; padding_x: number; row_height_mm: number; empty_row_height_mm: number; width_percent: number; header_height_mm: number; margin_top_mm: number; margin_bottom_mm: number; horizontal_borders: boolean; vertical_borders: boolean; columns: { reference: number; designation: number; presentation: number; quantity: number; unit_price: number; line_total: number; discount: number; total: number } };
    totals: { visible: boolean; width_percent: number; alignment: Alignment; background_color: string; grand_background_color: string; label_color: string; amount_color: string; label_weight: number; amount_weight: number; grand_weight: number; padding_y: number; padding_x: number; border_color: string; border_width: BorderWidth; label_font_size: number; amount_font_size: number; grand_font_size: number; label_column_width: number; amount_column_width: number; margin_top_mm: number; margin_bottom_mm: number; row_height_mm: number; border_opacity: number; border_style: 'solid' | 'dashed' | 'dotted'; outer_border: boolean; horizontal_borders: boolean; vertical_separator: boolean; final_label_font_size: number; final_amount_font_size: number; final_label_color: string; final_amount_color: string };
    amount_words: { visible: boolean; alignment: Alignment; background_color: string; intro_color: string; amount_color: string; intro_weight: number; amount_weight: number; padding_y: number; padding_x: number; margin_top_mm: number; margin_bottom_mm: number; width_percent: number; border_visible: boolean; border_opacity: number; border_color: string; border_width: BorderWidth; intro_font_size: number; intro_font_family: 'DejaVu Sans' | 'Helvetica'; intro_alignment: Alignment; intro_line_height: number; intro_letter_spacing_em: number; amount_font_size: number; amount_font_family: 'DejaVu Sans' | 'Helvetica'; amount_alignment: Alignment; amount_line_height: number; amount_letter_spacing_em: number };
    document_header: { visible: boolean; font_size: number; text_color: string; border_color: string; border_width: BorderWidth; height_mm: number; margin_bottom_mm: number };
    footer: { visible: boolean; font_size: number; text_color: string; border_color: string; border_width: BorderWidth; margin_top_mm: number };
    pagination: { visible: boolean; position: 'top' | 'bottom'; alignment: Alignment; font_family: 'DejaVu Sans' | 'Helvetica'; font_size: number; color: string; margin_x_mm: number; margin_y_mm: number };
    watermark: { visible: boolean };
    stamp: { visible: boolean; position_anchor: 'bottom_left' | 'bottom_right' | 'top_left' | 'top_right'; offset_x_mm: number; offset_y_mm: number; display_width_mm: number; display_height_mm: number | null; rotation_deg: number; opacity: number; preserve_aspect_ratio: boolean };
};
type Props = { organization: { id: number; name: string }; logoUrl: string | null; stampUrl: string | null; defaults: PdfTemplate; published: PdfTemplate; draft: PdfTemplate | null; canUpdate: boolean };

const sections = [
    ['page', 'Page & format', 'Page & marque'], ['logo', 'Logo', 'Page & marque'], ['company_name', "Nom de l’entreprise", 'Page & marque'], ['company_info', 'Informations entreprise', 'Page & marque'],
    ['recipient', 'Destinataire', 'Client & document'], ['document_title', 'Titre du document', 'Client & document'], ['document_info', 'Tableau informations document', 'Client & document'],
    ['items', 'Tableau articles', 'Contenu commercial'], ['totals', 'Tableau totaux', 'Contenu commercial'], ['words', 'Montant en lettres', 'Contenu commercial'],
    ['stamp', 'Cachet', 'Finalisation'], ['header', 'En-tête', 'Finalisation'], ['footer', 'Pied', 'Finalisation'], ['pagination', 'Pagination', 'Finalisation'],
] as const;
type SectionKey = (typeof sections)[number][0];

export default function TemplateStudio({ organization, logoUrl, stampUrl, defaults, published, draft, canUpdate }: Props) {
    const initial = useMemo(() => draft ?? published ?? defaults, [draft, published, defaults]);
    const form = useForm<{ mode: 'draft' | 'publish'; template: PdfTemplate }>({ mode: 'draft', template: initial });
    const resetForm = useForm({});
    const [active, setActive] = useState<SectionKey>('page');
    const [leftOpen, setLeftOpen] = useState(true);
    const [rightOpen, setRightOpen] = useState(true);
    const [mobilePanel, setMobilePanel] = useState<'sections' | 'properties' | null>(null);
    const [zoom, setZoom] = useState<'page-fit' | 'page-width' | number>('page-fit');
    const [page, setPage] = useState(1);
    const [previewUrl, setPreviewUrl] = useState<string | null>(null);
    const [previewing, setPreviewing] = useState(false);
    const [previewError, setPreviewError] = useState<string | null>(null);
    const canvasRef = useRef<HTMLDivElement>(null);

    const setPath = (path: string, value: unknown) => {
        const next = structuredClone(form.data.template) as PdfTemplate;
        const keys = path.split('.');
        let cursor = next as unknown as Record<string, unknown>;
        keys.slice(0, -1).forEach((key) => { cursor = cursor[key] as Record<string, unknown>; });
        cursor[keys.at(-1)!] = value;
        form.setData('template', next);
    };

    useEffect(() => {
        const controller = new AbortController();
        const timer = window.setTimeout(async () => {
            setPreviewing(true); setPreviewError(null);
            try {
                const token = document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content ?? '';
                const response = await fetch('/document-profile/studio/preview', { method: 'POST', signal: controller.signal, credentials: 'same-origin', headers: { 'Content-Type': 'application/json', Accept: 'application/pdf', 'X-CSRF-TOKEN': token, 'X-Requested-With': 'XMLHttpRequest' }, body: JSON.stringify({ template: form.data.template }) });
                if (!response.ok) throw new Error('preview');
                const nextUrl = URL.createObjectURL(await response.blob());
                setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return nextUrl; });
            } catch (error) { if ((error as Error).name !== 'AbortError') setPreviewError("L’aperçu PDF n’a pas pu être généré."); }
            finally { if (!controller.signal.aborted) setPreviewing(false); }
        }, 550);
        return () => { window.clearTimeout(timer); controller.abort(); };
    }, [form.data.template]);
    useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);

    const save = (mode: 'draft' | 'publish') => { form.setData('mode', mode); form.transform((data) => ({ ...data, mode })); form.put('/document-profile/studio', { preserveScroll: true }); };
    const submit = (event: FormEvent) => { event.preventDefault(); save('draft'); };
    const resetSection = () => {
        const next = structuredClone(form.data.template) as unknown as Record<string, unknown>;
        const source = defaults as unknown as Record<string, unknown>;
        const keys: Record<SectionKey, string[]> = { page: ['page', 'brand', 'watermark'], logo: ['logo'], company_name: ['company_name'], company_info: ['company_block'], recipient: ['recipient_block'], document_title: ['document_title'], document_info: ['document_info'], items: ['item_table'], totals: ['totals'], words: ['amount_words'], stamp: ['stamp'], header: ['document_header'], footer: ['footer'], pagination: ['pagination'] };
        keys[active].forEach((key) => { next[key] = structuredClone(source[key]); });
        form.setData('template', next as unknown as PdfTemplate);
    };
    const iframeSrc = previewUrl ? `${previewUrl}#page=${page}&zoom=${typeof zoom === 'number' ? zoom : zoom}&toolbar=0&navpanes=0` : undefined;

    const properties = <form onSubmit={submit} className="space-y-4"><fieldset disabled={!canUpdate || form.processing || resetForm.processing} className="space-y-4"><Inspector active={active} template={form.data.template} setPath={setPath} logoUrl={logoUrl} stampUrl={stampUrl} /><div className="grid gap-2 border-t border-line pt-4"><Button type="button" variant="ghost" size="sm" onClick={resetSection}>Réinitialiser cette section</Button><Button type="submit" variant="secondary" size="sm">Enregistrer brouillon</Button><Button type="button" size="sm" onClick={() => save('publish')}>Publier le modèle</Button><Button type="button" variant="ghost" size="sm" loading={resetForm.processing} onClick={() => resetForm.delete('/document-profile/studio', { preserveScroll: true, onSuccess: () => form.setData('template', defaults) })}>Réinitialiser tout</Button></div></fieldset></form>;
    return <ApplicationShell wide flush><Head title="Studio PDF" /><div className="flex h-full min-h-0 flex-col bg-canvas">
        <header className="flex shrink-0 flex-wrap items-center justify-between gap-3 border-b border-line bg-surface px-4 py-3"><div><div className="flex items-center gap-2"><h1 className="text-lg font-semibold text-ink">Studio PDF</h1>{form.isDirty && <span className="rounded-full bg-warning-soft px-2 py-0.5 text-[11px] font-medium text-warning">Modifications non enregistrées</span>}</div><p className="text-xs text-ink-muted">Modèle commercial de {organization.name} · aperçu Dompdf réel</p></div><div className="flex flex-wrap items-center gap-2"><ButtonLink href="/document-profile" variant="ghost" size="sm">Société</ButtonLink><Button type="button" variant="secondary" size="sm" disabled={!canUpdate} loading={form.processing && form.data.mode === 'draft'} onClick={() => save('draft')}>Enregistrer brouillon</Button><Button type="button" size="sm" disabled={!canUpdate} loading={form.processing && form.data.mode === 'publish'} onClick={() => save('publish')}>Publier</Button></div></header>
        {!canUpdate && <div className="shrink-0 border-b border-line bg-warning-soft px-4 py-2 text-xs text-warning">Mode lecture seule.</div>}
        <div className="flex min-h-0 flex-1">
            <aside className={`${leftOpen ? 'w-[248px]' : 'w-11'} hidden shrink-0 overflow-y-auto border-r border-line bg-surface transition-[width] xl:block`}><PanelHeader label="Sections" open={leftOpen} onToggle={() => setLeftOpen((v) => !v)} side="left" />{leftOpen && <SectionNavigation active={active} onSelect={setActive} />}</aside>
            <main className="flex min-h-0 min-w-0 flex-1 flex-col bg-slate-200/80"><div className="flex shrink-0 flex-wrap items-center justify-between gap-2 border-b border-line bg-surface px-3 py-2"><div className="flex gap-1"><button className="tool" type="button" onClick={() => setLeftOpen((v) => !v)}>Sections</button><button className="tool" type="button" onClick={() => setRightOpen((v) => !v)}>Propriétés</button></div><div className="flex flex-wrap items-center gap-1"><button className="tool" type="button" onClick={() => setZoom((z) => typeof z === 'number' ? Math.max(50, z - 10) : 90)}>−</button><button className="tool min-w-16" type="button" onClick={() => setZoom(100)}>{typeof zoom === 'number' ? `${zoom}%` : zoom === 'page-fit' ? 'Page' : 'Largeur'}</button><button className="tool" type="button" onClick={() => setZoom((z) => typeof z === 'number' ? Math.min(150, z + 10) : 110)}>+</button><button className="tool" type="button" onClick={() => setZoom('page-fit')}>Ajuster page</button><button className="tool" type="button" onClick={() => setZoom('page-width')}>Ajuster largeur</button><span className="mx-1 h-5 border-l border-line" /><button className="tool" type="button" onClick={() => setPage((p) => Math.max(1, p - 1))}>‹</button><span className="px-1 text-xs text-ink-muted">Page {page}</span><button className="tool" type="button" onClick={() => setPage((p) => p + 1)}>›</button><button className="tool" type="button" onClick={() => canvasRef.current?.requestFullscreen()}>Plein écran</button></div></div><div ref={canvasRef} className="relative min-h-0 flex-1 overflow-auto bg-slate-300 p-3 sm:p-6">{previewing && <span className="absolute right-4 top-4 z-10 rounded-full bg-surface px-3 py-1 text-xs text-ink-muted shadow-soft">Actualisation…</span>}{previewError ? <div className="mx-auto max-w-md rounded-card border border-danger/30 bg-danger-soft p-4 text-sm text-danger">{previewError}</div> : iframeSrc ? <iframe key={iframeSrc} src={iframeSrc} title="Aperçu PDF réel" className="mx-auto block h-full min-h-[760px] w-full max-w-[980px] border-0 bg-white shadow-2xl" /> : <div className="flex h-full items-center justify-center text-sm text-ink-muted">Génération de l’aperçu PDF…</div>}</div></main>
            <aside className={`${rightOpen ? 'w-[370px]' : 'w-11'} hidden shrink-0 overflow-y-auto border-l border-line bg-surface transition-[width] xl:block`}><PanelHeader label="Propriétés" open={rightOpen} onToggle={() => setRightOpen((v) => !v)} side="right" />{rightOpen && <div className="p-4">{properties}</div>}</aside>
        </div>
        <div className="fixed inset-x-3 bottom-3 z-30 flex gap-2 xl:hidden"><Button type="button" variant="secondary" className="flex-1" onClick={() => setMobilePanel('sections')}>Sections</Button><Button type="button" className="flex-1" onClick={() => setMobilePanel('properties')}>Propriétés</Button></div>
        {mobilePanel === 'sections' && <MobilePanel title="Sections" onClose={() => setMobilePanel(null)}><SectionNavigation active={active} onSelect={(key) => { setActive(key); setMobilePanel('properties'); }} /></MobilePanel>}
        {mobilePanel === 'properties' && <MobilePanel title="Propriétés" onClose={() => setMobilePanel(null)}>{properties}</MobilePanel>}
    </div></ApplicationShell>;
}

function Inspector({ active, template: t, setPath, logoUrl, stampUrl }: { active: SectionKey; template: PdfTemplate; setPath: (path: string, value: unknown) => void; logoUrl: string | null; stampUrl: string | null }) {
    const n = (label: string, path: string, value: number | null, min: number, max: number, step = .1, unit = 'pt') => <NumberField label={label} value={value ?? 0} min={min} max={max} step={step} suffix={unit} onChange={(v) => setPath(path, v)} />;
    const align = (path: string, value: string) => <SelectField label="Alignement" value={value} options={alignmentOptions} onChange={(v) => setPath(path, v)} />;
    return <><h2 className="text-sm font-semibold text-ink">{sections.find(([key]) => key === active)?.[1]}</h2>
        {active === 'page' && <Panel title="Page A4 & marque"><ColorField label="Couleur de marque" value={t.brand.accent_color} onChange={(v) => setPath('brand.accent_color', v)} /><ColorField label="Couleur du texte" value={t.page.text_color} onChange={(v) => setPath('page.text_color', v)} />{n('Corps général', 'page.base_font_size', t.page.base_font_size, 8, 12)}{n('Interligne', 'page.line_height', t.page.line_height, 1.1, 1.8, .01, '×')}<div className="grid grid-cols-2 gap-2">{n('Marge haut', 'page.margin_top_mm', t.page.margin_top_mm, 10, 35, 1, 'mm')}{n('Marge droite', 'page.margin_right_mm', t.page.margin_right_mm, 8, 30, 1, 'mm')}{n('Marge bas', 'page.margin_bottom_mm', t.page.margin_bottom_mm, 15, 40, 1, 'mm')}{n('Marge gauche', 'page.margin_left_mm', t.page.margin_left_mm, 8, 30, 1, 'mm')}</div><ToggleField label="Afficher le filigrane" checked={t.watermark.visible} onChange={(v) => setPath('watermark.visible', v)} /></Panel>}
        {active === 'logo' && <Panel title="Logo réel de l’organisation">{logoUrl ? <img src={logoUrl} alt="Logo" className="max-h-20 max-w-full object-contain" /> : <Empty>Aucun logo téléversé</Empty>}<ToggleField label="Afficher" checked={t.logo.visible} onChange={(v) => setPath('logo.visible', v)} />{n('Largeur maximale', 'logo.max_width_mm', t.logo.max_width_mm, 30, 100, 1, 'mm')}{n('Hauteur maximale', 'logo.max_height_mm', t.logo.max_height_mm, 12, 40, 1, 'mm')}{n('Espace sous le logo', 'logo.margin_bottom_mm', t.logo.margin_bottom_mm, 0, 12, .5, 'mm')}{align('logo.alignment', t.logo.alignment)}<ToggleField label="Préserver les proportions" checked={t.logo.preserve_aspect_ratio} onChange={(v) => setPath('logo.preserve_aspect_ratio', v)} /></Panel>}
        {active === 'company_name' && <TypographyEditor prefix="company_name" value={t.company_name} setPath={setPath}><SelectField label="Casse" value={t.company_name.text_transform} options={[['none','Normale'],['uppercase','Majuscules']]} onChange={(v) => setPath('company_name.text_transform', v)} /><SelectField label="Position par rapport au logo" value={t.company_name.position} options={[['above_logo','Au-dessus'],['below_logo','En dessous'],['beside_logo','À côté']]} onChange={(v) => setPath('company_name.position', v)} />{n('Espace avec le logo', 'company_name.logo_spacing_mm', t.company_name.logo_spacing_mm, 0, 20, .5, 'mm')}{n('Largeur disponible', 'company_name.width_percent', t.company_name.width_percent, 20, 100, 1, '%')}<div className="grid grid-cols-2 gap-2">{n('Marge gauche', 'company_name.margin_left_mm', t.company_name.margin_left_mm, 0, 30, .5, 'mm')}{n('Marge droite', 'company_name.margin_right_mm', t.company_name.margin_right_mm, 0, 30, .5, 'mm')}</div>{n('Position horizontale', 'company_name.horizontal_offset_mm', t.company_name.horizontal_offset_mm, -40, 40, .5, 'mm')}</TypographyEditor>}
        {active === 'company_info' && <><BoxEditor prefix="company_block" value={t.company_block} setPath={setPath} n={n} /><Panel title="Champs visibles"><ToggleField label="Adresse" checked={t.company_block.show_address} onChange={(v) => setPath('company_block.show_address', v)} /><ToggleField label="ICE" checked={t.company_block.show_tax_identifier} onChange={(v) => setPath('company_block.show_tax_identifier', v)} /><ToggleField label="Téléphone" checked={t.company_block.show_phone} onChange={(v) => setPath('company_block.show_phone', v)} /><ToggleField label="Email" checked={t.company_block.show_email} onChange={(v) => setPath('company_block.show_email', v)} /><ToggleField label="RC" checked={t.company_block.show_registration_number} onChange={(v) => setPath('company_block.show_registration_number', v)} /><ToggleField label="Patente" checked={t.company_block.show_patente_number} onChange={(v) => setPath('company_block.show_patente_number', v)} /><ToggleField label="Autres identifiants" checked={t.company_block.show_additional_identifiers} onChange={(v) => setPath('company_block.show_additional_identifiers', v)} /></Panel></>}
        {active === 'recipient' && <><BoxEditor prefix="recipient_block" value={t.recipient_block} setPath={setPath} n={n} /><TextGroupEditor title="En-tête Destinataire" prefix="recipient_block.heading" value={t.recipient_block.heading} setPath={setPath} /><TextGroupEditor title="Nom / société" prefix="recipient_block.name" value={t.recipient_block.name} setPath={setPath} /><TextGroupEditor title="Personne de contact" prefix="recipient_block.contact" value={t.recipient_block.contact} setPath={setPath} /><Panel title="Champs visibles"><ToggleField label="Adresse" checked={t.recipient_block.show_address} onChange={(v) => setPath('recipient_block.show_address', v)} /><ToggleField label="Téléphone" checked={t.recipient_block.show_phone} onChange={(v) => setPath('recipient_block.show_phone', v)} /><ToggleField label="Email" checked={t.recipient_block.show_email} onChange={(v) => setPath('recipient_block.show_email', v)} /><ToggleField label="Identifiant fiscal" checked={t.recipient_block.show_tax_identifier} onChange={(v) => setPath('recipient_block.show_tax_identifier', v)} /></Panel></>}
        {active === 'document_title' && <TypographyEditor prefix="document_title" value={t.document_title} setPath={setPath}><SelectField label="Casse" value={t.document_title.text_transform} options={[['none','Normale'],['uppercase','Majuscules']]} onChange={(v) => setPath('document_title.text_transform', v)} />{n('Largeur disponible', 'document_title.width_percent', t.document_title.width_percent, 30, 100, 1, '%')}<div className="grid grid-cols-2 gap-2">{n('Marge gauche', 'document_title.margin_left_mm', t.document_title.margin_left_mm, 0, 30, .5, 'mm')}{n('Marge droite', 'document_title.margin_right_mm', t.document_title.margin_right_mm, 0, 30, .5, 'mm')}</div></TypographyEditor>}
        {active === 'document_info' && <><Panel title="Libellés & valeurs"><ToggleField label="Afficher le tableau" checked={t.document_info.visible} onChange={(v) => setPath('document_info.visible', v)} />{n('Taille libellés', 'document_info.label_font_size', t.document_info.label_font_size, 8, 14)}{n('Taille valeurs', 'document_info.value_font_size', t.document_info.value_font_size, 8, 12)}{n('Graisse libellés', 'document_info.label_weight', t.document_info.label_weight, 400, 800, 100, '')}{n('Graisse valeurs', 'document_info.value_weight', t.document_info.value_weight, 400, 800, 100, '')}<ColorField label="Couleur libellés" value={t.document_info.label_color} onChange={(v) => setPath('document_info.label_color', v)} /><ColorField label="Couleur valeurs" value={t.document_info.value_color} onChange={(v) => setPath('document_info.value_color', v)} /><ColorField label="Fond libellés" value={t.document_info.header_background} onChange={(v) => setPath('document_info.header_background', v)} /><ColorField label="Fond valeurs" value={t.document_info.value_background} onChange={(v) => setPath('document_info.value_background', v)} /></Panel><Panel title="Dimensions & bordures"><ColorField label="Bordure" value={t.document_info.border_color} onChange={(v) => setPath('document_info.border_color', v)} /><SelectField label="Épaisseur" value={t.document_info.border_width} options={borderOptions} onChange={(v) => setPath('document_info.border_width', v)} />{n('Espacement vertical', 'document_info.padding_y', t.document_info.padding_y, 2, 8, .5, 'px')}{n('Marge basse', 'document_info.margin_bottom_mm', t.document_info.margin_bottom_mm, 0, 15, .5, 'mm')}<div className="grid grid-cols-2 gap-2">{[1,2,3,4].map((i) => n(`Colonne ${i}`, `document_info.column_${i}_width`, t.document_info[`column_${i}_width` as keyof typeof t.document_info] as number, 10, 50, 1, '%'))}</div></Panel></>}
        {active === 'document_info' && <Panel title="Bordures avancées"><ToggleField label="Bordure extérieure" checked={t.document_info.outer_border} onChange={(v) => setPath('document_info.outer_border', v)} /><ToggleField label="Séparateurs horizontaux" checked={t.document_info.inner_horizontal_borders} onChange={(v) => setPath('document_info.inner_horizontal_borders', v)} /><ToggleField label="Séparateurs verticaux" checked={t.document_info.inner_vertical_borders} onChange={(v) => setPath('document_info.inner_vertical_borders', v)} />{n('Opacité', 'document_info.border_opacity', t.document_info.border_opacity, 0, 100, 1, '%')}<SelectField label="Style" value={t.document_info.border_style} options={lineStyleOptions} onChange={(v) => setPath('document_info.border_style', v)} />{n('Largeur du tableau', 'document_info.width_percent', t.document_info.width_percent, 40, 100, 1, '%')}{n('Hauteur de ligne', 'document_info.row_height_mm', t.document_info.row_height_mm, 4, 20, .5, 'mm')}<SelectField label="Alignement libellés" value={t.document_info.label_alignment} options={alignmentOptions} onChange={(v) => setPath('document_info.label_alignment', v)} /><SelectField label="Alignement valeurs" value={t.document_info.value_alignment} options={alignmentOptions} onChange={(v) => setPath('document_info.value_alignment', v)} /></Panel>}
        {active === 'items' && <><Panel title="En-tête, lignes & grille"><ColorField label="Fond en-tête" value={t.item_table.header_background} onChange={(v) => setPath('item_table.header_background', v)} /><ColorField label="Texte en-tête" value={t.item_table.header_text} onChange={(v) => setPath('item_table.header_text', v)} />{n('Taille en-tête', 'item_table.header_font_size', t.item_table.header_font_size, 6.5, 10)}{n('Graisse en-tête', 'item_table.header_font_weight', t.item_table.header_font_weight, 400, 800, 100, '')}<ColorField label="Texte lignes" value={t.item_table.body_text_color} onChange={(v) => setPath('item_table.body_text_color', v)} />{n('Taille lignes', 'item_table.body_font_size', t.item_table.body_font_size, 7, 11)}<ColorField label="Séparateurs" value={t.item_table.separator_color} onChange={(v) => setPath('item_table.separator_color', v)} />{n('Opacité', 'item_table.separator_opacity', t.item_table.separator_opacity, 0, 100, 1, '%')}<SelectField label="Épaisseur" value={t.item_table.separator_thickness} options={thicknessOptions} onChange={(v) => setPath('item_table.separator_thickness', v)} /><SelectField label="Style" value={t.item_table.separator_style} options={lineStyleOptions} onChange={(v) => setPath('item_table.separator_style', v)} /><ToggleField label="Lignes horizontales" checked={t.item_table.horizontal_borders} onChange={(v) => setPath('item_table.horizontal_borders', v)} /><ToggleField label="Lignes verticales" checked={t.item_table.vertical_borders} onChange={(v) => setPath('item_table.vertical_borders', v)} /></Panel><Panel title="Dimensions & espacement">{n('Largeur', 'item_table.width_percent', t.item_table.width_percent, 50, 100, 1, '%')}{n('Hauteur en-tête', 'item_table.header_height_mm', t.item_table.header_height_mm, 4, 15, .5, 'mm')}{n('Hauteur ligne', 'item_table.row_height_mm', t.item_table.row_height_mm, 3, 12, .5, 'mm')}{n('Hauteur ligne vide', 'item_table.empty_row_height_mm', t.item_table.empty_row_height_mm, 3, 10, .5, 'mm')}<div className="grid grid-cols-2 gap-2">{n('Marge avant', 'item_table.margin_top_mm', t.item_table.margin_top_mm, 0, 15, .5, 'mm')}{n('Marge après', 'item_table.margin_bottom_mm', t.item_table.margin_bottom_mm, 0, 15, .5, 'mm')}</div></Panel></>}
        {active === 'totals' && <Panel title="Tableau totaux"><ToggleField label="Afficher" checked={t.totals.visible} onChange={(v) => setPath('totals.visible', v)} />{n('Largeur', 'totals.width_percent', t.totals.width_percent, 30, 100, 1, '%')}{align('totals.alignment', t.totals.alignment)}<ColorField label="Fond" value={t.totals.background_color} onChange={(v) => setPath('totals.background_color', v)} /><ColorField label="Fond total TTC" value={t.totals.grand_background_color} onChange={(v) => setPath('totals.grand_background_color', v)} /><ColorField label="Libellés" value={t.totals.label_color} onChange={(v) => setPath('totals.label_color', v)} /><ColorField label="Montants" value={t.totals.amount_color} onChange={(v) => setPath('totals.amount_color', v)} />{n('Taille libellés', 'totals.label_font_size', t.totals.label_font_size, 7.5, 12)}{n('Taille montants', 'totals.amount_font_size', t.totals.amount_font_size, 7.5, 12)}{n('Taille total TTC', 'totals.grand_font_size', t.totals.grand_font_size, 9, 15)}<ColorField label="Bordures" value={t.totals.border_color} onChange={(v) => setPath('totals.border_color', v)} /><SelectField label="Épaisseur" value={t.totals.border_width} options={borderOptions} onChange={(v) => setPath('totals.border_width', v)} /></Panel>}
        {active === 'words' && <Panel title="Montant en lettres"><ToggleField label="Afficher" checked={t.amount_words.visible} onChange={(v) => setPath('amount_words.visible', v)} />{align('amount_words.alignment', t.amount_words.alignment)}<ColorField label="Fond" value={t.amount_words.background_color} onChange={(v) => setPath('amount_words.background_color', v)} /><ColorField label="Introduction" value={t.amount_words.intro_color} onChange={(v) => setPath('amount_words.intro_color', v)} /><ColorField label="Montant" value={t.amount_words.amount_color} onChange={(v) => setPath('amount_words.amount_color', v)} />{n('Taille introduction', 'amount_words.intro_font_size', t.amount_words.intro_font_size, 7.5, 12)}{n('Taille montant', 'amount_words.amount_font_size', t.amount_words.amount_font_size, 9, 16)}<ColorField label="Bordure" value={t.amount_words.border_color} onChange={(v) => setPath('amount_words.border_color', v)} /><SelectField label="Épaisseur" value={t.amount_words.border_width} options={borderOptions} onChange={(v) => setPath('amount_words.border_width', v)} />{n('Marge haute', 'amount_words.margin_top_mm', t.amount_words.margin_top_mm, 0, 15, .5, 'mm')}</Panel>}
        {active === 'totals' && <Panel title="Structure & total final"><div className="grid grid-cols-2 gap-2">{n('Colonne libellés', 'totals.label_column_width', t.totals.label_column_width, 20, 80, 1, '%')}{n('Colonne montants', 'totals.amount_column_width', t.totals.amount_column_width, 20, 80, 1, '%')}</div>{n('Hauteur ligne', 'totals.row_height_mm', t.totals.row_height_mm, 3, 15, .5, 'mm')}<div className="grid grid-cols-2 gap-2">{n('Marge avant', 'totals.margin_top_mm', t.totals.margin_top_mm, 0, 20, .5, 'mm')}{n('Marge après', 'totals.margin_bottom_mm', t.totals.margin_bottom_mm, 0, 20, .5, 'mm')}</div><ToggleField label="Bordure extérieure" checked={t.totals.outer_border} onChange={(v) => setPath('totals.outer_border', v)} /><ToggleField label="Séparateurs horizontaux" checked={t.totals.horizontal_borders} onChange={(v) => setPath('totals.horizontal_borders', v)} /><ToggleField label="Séparateur vertical" checked={t.totals.vertical_separator} onChange={(v) => setPath('totals.vertical_separator', v)} />{n('Opacité bordures', 'totals.border_opacity', t.totals.border_opacity, 0, 100, 1, '%')}<SelectField label="Style bordures" value={t.totals.border_style} options={lineStyleOptions} onChange={(v) => setPath('totals.border_style', v)} />{n('Libellé Total TTC', 'totals.final_label_font_size', t.totals.final_label_font_size, 8, 18)}{n('Montant Total TTC', 'totals.final_amount_font_size', t.totals.final_amount_font_size, 8, 18)}<ColorField label="Couleur libellé final" value={t.totals.final_label_color} onChange={(v) => setPath('totals.final_label_color', v)} /><ColorField label="Couleur montant final" value={t.totals.final_amount_color} onChange={(v) => setPath('totals.final_amount_color', v)} /></Panel>}
        {active === 'words' && <><Panel title="Dimensions & bordure">{n('Largeur', 'amount_words.width_percent', t.amount_words.width_percent, 30, 100, 1, '%')}<div className="grid grid-cols-2 gap-2">{n('Marge avant', 'amount_words.margin_top_mm', t.amount_words.margin_top_mm, 0, 15, .5, 'mm')}{n('Marge après', 'amount_words.margin_bottom_mm', t.amount_words.margin_bottom_mm, 0, 15, .5, 'mm')}</div><ToggleField label="Afficher la bordure" checked={t.amount_words.border_visible} onChange={(v) => setPath('amount_words.border_visible', v)} />{n('Opacité bordure', 'amount_words.border_opacity', t.amount_words.border_opacity, 0, 100, 1, '%')}</Panel><Panel title="Introduction"><SelectField label="Police" value={t.amount_words.intro_font_family} options={fontOptions} onChange={(v) => setPath('amount_words.intro_font_family', v)} /><SelectField label="Alignement" value={t.amount_words.intro_alignment} options={alignmentOptions} onChange={(v) => setPath('amount_words.intro_alignment', v)} />{n('Interligne', 'amount_words.intro_line_height', t.amount_words.intro_line_height, 1, 2, .05, '×')}{n('Espacement lettres', 'amount_words.intro_letter_spacing_em', t.amount_words.intro_letter_spacing_em, 0, .2, .01, 'em')}</Panel><Panel title="Valeur en lettres"><SelectField label="Police" value={t.amount_words.amount_font_family} options={fontOptions} onChange={(v) => setPath('amount_words.amount_font_family', v)} /><SelectField label="Alignement" value={t.amount_words.amount_alignment} options={alignmentOptions} onChange={(v) => setPath('amount_words.amount_alignment', v)} />{n('Interligne', 'amount_words.amount_line_height', t.amount_words.amount_line_height, 1, 2, .05, '×')}{n('Espacement lettres', 'amount_words.amount_letter_spacing_em', t.amount_words.amount_letter_spacing_em, 0, .2, .01, 'em')}</Panel></>}
        {active === 'stamp' && <Panel title="Cachet & signature">{stampUrl ? <img src={stampUrl} alt="Cachet" className="max-h-24 max-w-full object-contain" /> : <Empty>Aucun cachet configuré</Empty>}<ToggleField label="Afficher lors de l’apposition" checked={t.stamp.visible} onChange={(v) => setPath('stamp.visible', v)} /><SelectField label="Position" value={t.stamp.position_anchor} options={[['bottom_left','Bas gauche'],['bottom_right','Bas droite'],['top_left','Haut gauche'],['top_right','Haut droite']]} onChange={(v) => setPath('stamp.position_anchor', v)} />{n('Décalage X', 'stamp.offset_x_mm', t.stamp.offset_x_mm, 0, 120, 1, 'mm')}{n('Décalage Y', 'stamp.offset_y_mm', t.stamp.offset_y_mm, 0, 180, 1, 'mm')}{n('Largeur', 'stamp.display_width_mm', t.stamp.display_width_mm, 20, 100, 1, 'mm')}{!t.stamp.preserve_aspect_ratio && n('Hauteur', 'stamp.display_height_mm', t.stamp.display_height_mm, 10, 100, 1, 'mm')}{n('Rotation', 'stamp.rotation_deg', t.stamp.rotation_deg, -20, 20, 1, '°')}{n('Opacité', 'stamp.opacity', t.stamp.opacity, 10, 100, 1, '%')}<ToggleField label="Préserver les proportions" checked={t.stamp.preserve_aspect_ratio} onChange={(v) => setPath('stamp.preserve_aspect_ratio', v)} /></Panel>}
        {active === 'header' && <Panel title="En-tête"><ToggleField label="Afficher" checked={t.document_header.visible} onChange={(v) => setPath('document_header.visible', v)} />{n('Hauteur', 'document_header.height_mm', t.document_header.height_mm, 8, 20, .5, 'mm')}{n('Texte', 'document_header.font_size', t.document_header.font_size, 7, 11)}<ColorField label="Couleur" value={t.document_header.text_color} onChange={(v) => setPath('document_header.text_color', v)} /><ColorField label="Séparateur" value={t.document_header.border_color} onChange={(v) => setPath('document_header.border_color', v)} /></Panel>}
        {active === 'footer' && <Panel title="Pied de page"><ToggleField label="Afficher" checked={t.footer.visible} onChange={(v) => setPath('footer.visible', v)} />{n('Texte', 'footer.font_size', t.footer.font_size, 6.5, 10)}<ColorField label="Couleur" value={t.footer.text_color} onChange={(v) => setPath('footer.text_color', v)} /><ColorField label="Séparateur" value={t.footer.border_color} onChange={(v) => setPath('footer.border_color', v)} /></Panel>}
        {active === 'pagination' && <Panel title="Pagination"><ToggleField label="Afficher" checked={t.pagination.visible} onChange={(v) => setPath('pagination.visible', v)} /><SelectField label="Position" value={t.pagination.position} options={[['bottom','Bas'],['top','Haut']]} onChange={(v) => setPath('pagination.position', v)} />{align('pagination.alignment', t.pagination.alignment)}<SelectField label="Police" value={t.pagination.font_family} options={fontOptions} onChange={(v) => setPath('pagination.font_family', v)} />{n('Taille', 'pagination.font_size', t.pagination.font_size, 6, 11)}<ColorField label="Couleur" value={t.pagination.color} onChange={(v) => setPath('pagination.color', v)} /></Panel>}
        {active === 'document_info' && <Panel title="Polices"><SelectField label="Police libellés" value={t.document_info.label_font_family} options={fontOptions} onChange={(v) => setPath('document_info.label_font_family', v)} /><SelectField label="Police valeurs" value={t.document_info.value_font_family} options={fontOptions} onChange={(v) => setPath('document_info.value_font_family', v)} /></Panel>}
        {active === 'items' && <Panel title="Largeurs des colonnes"><div className="grid grid-cols-2 gap-2">{Object.entries(t.item_table.columns).map(([column, width]) => n(columnLabels[column] ?? column, `item_table.columns.${column}`, width, 4, 50, 1, '%'))}</div><p className="text-[11px] text-ink-subtle">Les dimensions restent visuelles et ne modifient aucune donnée commerciale.</p></Panel>}
        {active === 'company_info' && <Panel title="Marges du bloc"><div className="grid grid-cols-2 gap-2">{n('Marge haute', 'company_block.margin_top_mm', t.company_block.margin_top_mm, 0, 20, .5, 'mm')}{n('Marge basse', 'company_block.margin_bottom_mm', t.company_block.margin_bottom_mm, 0, 20, .5, 'mm')}</div></Panel>}
        {active === 'recipient' && <Panel title="Espacement du bloc"><div className="grid grid-cols-2 gap-2">{n('Marge haute', 'recipient_block.margin_top_mm', t.recipient_block.margin_top_mm, 0, 40, .5, 'mm')}{n('Marge basse', 'recipient_block.margin_bottom_mm', t.recipient_block.margin_bottom_mm, 0, 20, .5, 'mm')}</div>{n('Titre vers contenu', 'recipient_block.heading_spacing_mm', t.recipient_block.heading_spacing_mm, 0, 10, .5, 'mm')}</Panel>}
        {active === 'words' && <Panel title="Graisses & espacements internes">{n('Graisse introduction', 'amount_words.intro_weight', t.amount_words.intro_weight, 400, 800, 100, '')}{n('Graisse montant', 'amount_words.amount_weight', t.amount_words.amount_weight, 400, 800, 100, '')}<div className="grid grid-cols-2 gap-2">{n('Padding vertical', 'amount_words.padding_y', t.amount_words.padding_y, 2, 18, .5, 'px')}{n('Padding horizontal', 'amount_words.padding_x', t.amount_words.padding_x, 2, 20, .5, 'px')}</div></Panel>}
    </>;
}

function TypographyEditor({ prefix, value, setPath, children }: { prefix: string; value: TypographyStyle; setPath: (path: string, value: unknown) => void; children?: ReactNode }) { return <Panel title="Typographie & placement"><ToggleField label="Afficher" checked={value.visible} onChange={(v) => setPath(`${prefix}.visible`, v)} /><SelectField label="Police" value={value.font_family} options={fontOptions} onChange={(v) => setPath(`${prefix}.font_family`, v)} /><NumberField label="Taille" value={value.font_size} min={7} max={36} step={.1} suffix="pt" onChange={(v) => setPath(`${prefix}.font_size`, v)} /><NumberField label="Graisse" value={value.font_weight} min={400} max={800} step={100} suffix="" onChange={(v) => setPath(`${prefix}.font_weight`, v)} /><ColorField label="Couleur" value={value.color} onChange={(v) => setPath(`${prefix}.color`, v)} /><NumberField label="Espacement lettres" value={value.letter_spacing_em} min={0} max={.2} step={.01} suffix="em" onChange={(v) => setPath(`${prefix}.letter_spacing_em`, v)} /><NumberField label="Interligne" value={value.line_height} min={1} max={2} step={.05} suffix="×" onChange={(v) => setPath(`${prefix}.line_height`, v)} /><SelectField label="Alignement" value={value.alignment} options={alignmentOptions} onChange={(v) => setPath(`${prefix}.alignment`, v)} /><div className="grid grid-cols-2 gap-2"><NumberField label="Marge haute" value={value.margin_top_mm} min={0} max={30} step={.5} suffix="mm" onChange={(v) => setPath(`${prefix}.margin_top_mm`, v)} /><NumberField label="Marge basse" value={value.margin_bottom_mm} min={0} max={30} step={.5} suffix="mm" onChange={(v) => setPath(`${prefix}.margin_bottom_mm`, v)} /></div>{children}</Panel>; }
function BoxEditor({ prefix, value, setPath, n }: { prefix: string; value: BoxStyle; setPath: (path: string, value: unknown) => void; n: (label: string, path: string, value: number | null, min: number, max: number, step?: number, unit?: string) => ReactNode }) { return <><Panel title="Dimensions, position & couleurs"><ToggleField label="Afficher le bloc" checked={value.visible} onChange={(v) => setPath(`${prefix}.visible`, v)} />{n('Largeur', `${prefix}.width_percent`, value.width_percent, 30, 100, 1, '%')}<SelectField label="Alignement du bloc" value={value.alignment} options={alignmentOptions} onChange={(v) => setPath(`${prefix}.alignment`, v)} />{n('Espacement interne', `${prefix}.padding_mm`, value.padding_mm, 0, 12, .5, 'mm')}{n('Espacement des lignes', `${prefix}.row_spacing_mm`, value.row_spacing_mm, 0, 5, .1, 'mm')}{n('Espace libellé / valeur', `${prefix}.label_gap_mm`, value.label_gap_mm, 0, 10, .5, 'mm')}<ColorField label="Fond" value={value.background_color} onChange={(v) => setPath(`${prefix}.background_color`, v)} /><ColorField label="Bordure" value={value.border_color} onChange={(v) => setPath(`${prefix}.border_color`, v)} /><SelectField label="Épaisseur" value={value.border_width} options={borderOptions} onChange={(v) => setPath(`${prefix}.border_width`, v)} /></Panel><TextGroupEditor title="Libellés" prefix={`${prefix}.labels`} value={value.labels} setPath={setPath} showWidth /><TextGroupEditor title="Valeurs" prefix={`${prefix}.values`} value={value.values} setPath={setPath} showWrap /></>; }
function TextGroupEditor({ title, prefix, value, setPath, showWidth = false, showWrap = false }: { title: string; prefix: string; value: TextGroup; setPath: (path: string, value: unknown) => void; showWidth?: boolean; showWrap?: boolean }) { return <Panel title={title}><SelectField label="Police" value={value.font_family} options={fontOptions} onChange={(v) => setPath(`${prefix}.font_family`, v)} /><NumberField label="Taille" value={value.font_size} min={6} max={20} step={.1} suffix="pt" onChange={(v) => setPath(`${prefix}.font_size`, v)} /><NumberField label="Graisse" value={value.font_weight} min={400} max={800} step={100} suffix="" onChange={(v) => setPath(`${prefix}.font_weight`, v)} /><ColorField label="Couleur" value={value.color} onChange={(v) => setPath(`${prefix}.color`, v)} /><NumberField label="Interligne" value={value.line_height} min={1} max={2} step={.05} suffix="×" onChange={(v) => setPath(`${prefix}.line_height`, v)} /><SelectField label="Alignement" value={value.alignment} options={alignmentOptions} onChange={(v) => setPath(`${prefix}.alignment`, v)} />{showWidth && <><NumberField label="Largeur colonne libellés" value={value.width_percent ?? 18} min={10} max={50} step={1} suffix="%" onChange={(v) => setPath(`${prefix}.width_percent`, v)} /><p className="text-[11px] text-ink-subtle">La colonne des valeurs utilise automatiquement l’espace restant.</p></>}{showWrap && <ToggleField label="Autoriser le retour à la ligne" checked={value.wrap ?? true} onChange={(v) => setPath(`${prefix}.wrap`, v)} />}</Panel>; }
function SectionNavigation({ active, onSelect }: { active: SectionKey; onSelect: (key: SectionKey) => void }) { const groups = [...new Set(sections.map(([, , group]) => group))]; return <nav className="space-y-4 p-2">{groups.map((group) => <div key={group}><div className="px-3 pb-1 text-[10px] font-semibold uppercase tracking-wider text-ink-subtle">{group}</div>{sections.filter(([, , itemGroup]) => itemGroup === group).map(([key, label]) => <button key={key} type="button" onClick={() => onSelect(key)} className={`mb-1 w-full rounded-field px-3 py-2 text-left text-sm ${active === key ? 'bg-primary text-primary-fg' : 'text-ink-muted hover:bg-raised hover:text-ink'}`}>{label}</button>)}</div>)}</nav>; }
function PanelHeader({ label, open, onToggle, side }: { label: string; open: boolean; onToggle: () => void; side: 'left' | 'right' }) { return <div className="flex items-center justify-between border-b border-line p-3">{side === 'right' && <button type="button" className="rounded p-1 text-ink-muted hover:bg-raised" onClick={onToggle}>{open ? '›' : '‹'}</button>}<span className={`${open ? 'block' : 'hidden'} text-xs font-semibold uppercase tracking-wide text-ink-muted`}>{label}</span>{side === 'left' && <button type="button" className="rounded p-1 text-ink-muted hover:bg-raised" onClick={onToggle}>{open ? '‹' : '›'}</button>}</div>; }
function MobilePanel({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-40 bg-ink/40 xl:hidden"><aside className="absolute inset-y-0 right-0 w-[90vw] max-w-sm overflow-y-auto bg-surface p-4 shadow-pop"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-ink">{title}</h2><button type="button" onClick={onClose} className="rounded-field px-3 py-2 text-ink-muted hover:bg-raised">Fermer</button></div>{children}</aside></div>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <details open className="group rounded-card border border-line bg-surface"><summary className="cursor-pointer list-none px-3 py-2 text-xs font-semibold text-ink">{title}</summary><div className="space-y-3 border-t border-line p-3">{children}</div></details>; }
function Empty({ children }: { children: ReactNode }) { return <div className="rounded-field border border-dashed border-line-strong bg-raised p-4 text-center text-xs text-ink-muted">{children}</div>; }
function NumberField({ label, value, min, max, step, suffix, onChange }: { label: string; value: number; min: number; max: number; step: number; suffix: string; onChange: (value: number) => void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-ink-muted">{label}</span><div className="flex items-center"><input type="number" value={value} min={min} max={max} step={step} onChange={(e) => Number.isFinite(Number(e.target.value)) && onChange(Number(e.target.value))} className="min-w-0 flex-1 rounded-l-field border border-line-strong bg-surface px-2.5 py-2 text-sm" /><span className="rounded-r-field border border-l-0 border-line-strong bg-raised px-2 py-2 text-xs text-ink-muted">{suffix || '—'}</span></div></label>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-ink-muted">{label}</span><div className="flex gap-2"><input type="color" value={value} onChange={(e) => onChange(e.target.value)} className="h-9 w-11 rounded-field border border-line-strong" /><input value={value} maxLength={7} onChange={(e) => onChange(e.target.value)} className="min-w-0 flex-1 rounded-field border border-line-strong px-2 py-1.5 text-sm" /></div></label>; }
function ToggleField({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 rounded-field border border-line bg-raised px-3 py-2 text-xs font-medium text-ink"><span>{label}</span><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /></label>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: [string, string][]; onChange: (value: string) => void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-ink-muted">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-field border border-line-strong bg-surface px-2.5 py-2 text-sm">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }

const alignmentOptions: [string, string][] = [['left', 'Gauche'], ['center', 'Centre'], ['right', 'Droite']];
const fontOptions: [string, string][] = [['DejaVu Sans', 'DejaVu Sans'], ['Helvetica', 'Helvetica']];
const lineStyleOptions: [string, string][] = [['solid', 'Continue'], ['dashed', 'Tirets'], ['dotted', 'Pointillée']];
const thicknessOptions: [string, string][] = [['fine', 'Fine'], ['normal', 'Normale'], ['thick', 'Épaisse']];
const borderOptions: [string, string][] = [['0pt', 'Aucune'], ['.45pt', 'Très fine'], ['.7pt', 'Fine'], ['.85pt', 'Normale'], ['.95pt', 'Soutenue'], ['1.1pt', 'Épaisse'], ['1.4pt', 'Très épaisse']];
const columnLabels: Record<string, string> = { reference: 'Référence', designation: 'Désignation', presentation: 'Présentation', quantity: 'Quantité', unit_price: 'P.U HT', line_total: 'P.T HT', discount: 'Remise', total: 'Total TTC' };
