import SalesLayout from '@/layouts/SalesLayout';
import { formatDate, formatDateTime, formatMoney, formatQuantity } from '@/utils/format';
import { Head, Link, router, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Line = { id: number; description: string; product_name: string | null; variant_name: string | null; sku: string | null; unit_label: string | null; quantity: string; unit_price_excl_tax: string; discount_amount: string; tax_name: string | null; tax_rate: string; tax_amount: string; total_incl_tax: string };
type Invoice = { id: number; invoice_number: string | null; status: string; invoice_date: string; customer_name: string | null; customer_company: string | null; customer_email: string | null; customer_phone: string | null; customer_tax_identifier: string | null; billing_address: string | null; notes: string | null; subtotal_excl_tax: string; discount_total: string; tax_total: string; total_incl_tax: string; currency_code: string; issued_at: string | null; cancellation_reason: string | null; store: { name: string; code: string }; sales_order: { id: number; order_number: string }; lines: Line[]; issued_by: { name: string } | null };
type Props = { invoice: Invoice; relatedOrderPaymentSummary: { paid: string; remaining: string; status: string }; can: { updateDraft: boolean; issue: boolean; backdate: boolean; email: boolean } };

export default function InvoiceShow({ invoice, relatedOrderPaymentSummary, can }: Props) {
    const form = useForm({ invoice_date: invoice.invoice_date.slice(0, 10), customer_name: invoice.customer_name ?? '', customer_company: invoice.customer_company ?? '', customer_email: invoice.customer_email ?? '', customer_phone: invoice.customer_phone ?? '', customer_tax_identifier: invoice.customer_tax_identifier ?? '', billing_address: invoice.billing_address ?? '', notes: invoice.notes ?? '' });
    const cancellation = useForm({ reason: '' });
    const email = useForm({ email: invoice.customer_email ?? '' });
    const update = (event: FormEvent) => { event.preventDefault(); form.patch(`/invoices/${invoice.id}`, { preserveScroll: true }); };
    const cancel = (event: FormEvent) => { event.preventDefault(); cancellation.post(`/invoices/${invoice.id}/cancel`, { preserveScroll: true }); };
    const sendEmail = (event: FormEvent) => { event.preventDefault(); email.post(`/invoices/${invoice.id}/email`, { preserveScroll: true }); };
    return <SalesLayout><Head title={invoice.invoice_number ?? `Invoice draft #${invoice.id}`} />
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href="/invoices" className="text-sm text-slate-500">← Invoices</Link><h2 className="mt-2 text-xl font-semibold">{invoice.invoice_number ?? `Invoice draft #${invoice.id}`}</h2><p className="text-sm text-slate-500">Order <Link href={`/sales/orders/${invoice.sales_order.id}`} className="underline">{invoice.sales_order.order_number}</Link> · {invoice.store.code} · {invoice.store.name}</p></div>{invoice.status === 'draft' && can.issue && <button onClick={() => router.post(`/invoices/${invoice.id}/issue`)} className="rounded bg-slate-900 px-4 py-2 text-white">Issue invoice</button>}</div>
        <section className="mb-6 grid gap-4 rounded-lg bg-slate-50 p-5 md:grid-cols-4"><div>Invoice date<br /><strong>{formatDate(invoice.invoice_date)}</strong></div><div>Status<br /><strong className="capitalize">{invoice.status}</strong></div><div>Total<br /><strong>{formatMoney(invoice.total_incl_tax, invoice.currency_code)}</strong></div><div>Issued<br /><strong>{invoice.issued_at ? `${invoice.issued_by?.name ?? 'Unknown'} · ${formatDateTime(invoice.issued_at)}` : 'Not issued'}</strong></div></section>
        <section className="mb-6 flex flex-wrap items-end gap-3 rounded-lg border p-5"><a href={`/invoices/${invoice.id}/print`} target="_blank" rel="noreferrer" className="rounded border px-4 py-2">{invoice.status === 'draft' ? 'Print preview' : 'Print'}</a>{invoice.status === 'issued' && <><a href={`/invoices/${invoice.id}/pdf`} target="_blank" rel="noreferrer" className="rounded border px-4 py-2">Open PDF</a><a href={`/invoices/${invoice.id}/download`} className="rounded border px-4 py-2">Download PDF</a></>}{invoice.status === 'issued' && can.email && <form onSubmit={sendEmail} className="flex flex-wrap items-end gap-2"><label className="text-sm">Recipient email<input type="email" required value={email.data.email} onChange={e => email.setData('email', e.target.value)} className="mt-1 block rounded border px-3 py-2" /></label><button disabled={email.processing} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50">{email.processing ? 'Sending…' : 'Email PDF'}</button>{email.errors.email && <span className="text-sm text-red-600">{email.errors.email}</span>}</form>}</section>
        {invoice.status === 'draft' && can.updateDraft && <form onSubmit={update} className="mb-6 grid gap-3 rounded-lg border p-5 md:grid-cols-2"><h3 className="font-semibold md:col-span-2">Draft billing information</h3><label className="text-sm">Invoice date<input type="date" readOnly={!can.backdate} value={form.data.invoice_date} onChange={(e) => form.setData('invoice_date', e.target.value)} className="mt-1 w-full rounded border px-3 py-2 read-only:bg-slate-100" /></label><label className="text-sm">Legal/display name<input value={form.data.customer_name} onChange={(e) => form.setData('customer_name', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Company<input value={form.data.customer_company} onChange={(e) => form.setData('customer_company', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Tax identifier<input value={form.data.customer_tax_identifier} onChange={(e) => form.setData('customer_tax_identifier', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Email<input type="email" value={form.data.customer_email} onChange={(e) => form.setData('customer_email', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Phone<input value={form.data.customer_phone} onChange={(e) => form.setData('customer_phone', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm md:col-span-2">Billing address<textarea value={form.data.billing_address} onChange={(e) => form.setData('billing_address', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm md:col-span-2">Notes<textarea value={form.data.notes} onChange={(e) => form.setData('notes', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label>{Object.values(form.errors).map((error) => error && <p key={error} className="text-sm text-red-600 md:col-span-2">{error}</p>)}<button disabled={form.processing} className="w-fit rounded border px-4 py-2">Save draft</button></form>}
        {invoice.status !== 'draft' && <section className="mb-6 rounded-lg border p-5"><h3 className="font-semibold">Billing snapshot</h3><p className="mt-2">{invoice.customer_company ?? invoice.customer_name ?? 'Walk-in'}</p><p>{invoice.customer_tax_identifier}</p><p className="whitespace-pre-wrap">{invoice.billing_address}</p></section>}
        <div className="mb-6 overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Item</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Price</th><th className="p-3 text-right">Discount</th><th className="p-3 text-right">Tax</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id} className="border-t"><td className="p-3"><strong>{line.product_name ?? line.description}</strong><br /><span className="text-slate-500">{line.variant_name} {line.sku}</span></td><td className="p-3 text-right">{formatQuantity(line.quantity)} {line.unit_label}</td><td className="p-3 text-right">{formatMoney(line.unit_price_excl_tax, invoice.currency_code)}</td><td className="p-3 text-right">{formatMoney(line.discount_amount, invoice.currency_code)}</td><td className="p-3 text-right">{formatMoney(line.tax_amount, invoice.currency_code)}<br /><span className="text-slate-500">{line.tax_name} {line.tax_rate}%</span></td><td className="p-3 text-right">{formatMoney(line.total_incl_tax, invoice.currency_code)}</td></tr>)}</tbody></table></div>
        <section className="mb-6 ml-auto grid max-w-2xl grid-cols-2 gap-2 rounded-lg bg-slate-50 p-5 text-right"><span>Subtotal</span><strong>{formatMoney(invoice.subtotal_excl_tax, invoice.currency_code)}</strong><span>Discount</span><strong>{formatMoney(invoice.discount_total, invoice.currency_code)}</strong><span>Tax</span><strong>{formatMoney(invoice.tax_total, invoice.currency_code)}</strong><span>Total</span><strong>{formatMoney(invoice.total_incl_tax, invoice.currency_code)}</strong></section>
        <section className="mb-6 rounded-lg border p-5"><h3 className="font-semibold">Related Sales Order payment summary</h3><p className="mt-2 text-sm text-slate-600">This is Order-level payment information, not an Invoice allocation.</p><p className="mt-2">Paid {formatMoney(relatedOrderPaymentSummary.paid, invoice.currency_code)} · Remaining {formatMoney(relatedOrderPaymentSummary.remaining, invoice.currency_code)} · <span className="capitalize">{relatedOrderPaymentSummary.status.replaceAll('_', ' ')}</span></p></section>
        {invoice.status === 'draft' && can.updateDraft && <form onSubmit={cancel} className="max-w-xl space-y-3 rounded-lg border border-red-200 p-5"><h3 className="font-semibold text-red-800">Cancel draft</h3><textarea value={cancellation.data.reason} onChange={(e) => cancellation.setData('reason', e.target.value)} placeholder="Reason (optional)" className="w-full rounded border px-3 py-2" /><button className="rounded border border-red-300 px-4 py-2 text-red-800">Cancel draft</button></form>}
        {invoice.status === 'cancelled' && <p className="rounded-lg bg-amber-50 p-5">Cancelled draft: {invoice.cancellation_reason ?? 'No reason supplied'}</p>}
    </SalesLayout>;
}
