import SalesLayout from '@/layouts/SalesLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Line = { id: number; description: string; product_name: string | null; variant_name: string | null; sku: string | null; reference: string | null; unit_label: string | null; quantity: string };
type Note = { id: number; delivery_note_number: string | null; status: string; delivery_date: string; recipient_name: string | null; recipient_company: string | null; recipient_phone: string | null; delivery_address: string | null; notes: string | null; issued_at: string | null; cancellation_reason: string | null; store: { name: string; code: string }; sales_order: { id: number; order_number: string }; lines: Line[]; issued_by: { name: string } | null };
type Props = { deliveryNote: Note; can: { updateDraft: boolean; issue: boolean; backdate: boolean; email: boolean } };

export default function DeliveryNoteShow({ deliveryNote: note, can }: Props) {
    const form = useForm({ delivery_date: note.delivery_date.slice(0, 10), recipient_name: note.recipient_name ?? '', recipient_company: note.recipient_company ?? '', recipient_phone: note.recipient_phone ?? '', delivery_address: note.delivery_address ?? '', notes: note.notes ?? '' });
    const cancellation = useForm({ reason: '' });
    const email = useForm({ email: '' });
    const update = (event: FormEvent) => { event.preventDefault(); form.patch(`/delivery-notes/${note.id}`, { preserveScroll: true }); };
    const cancel = (event: FormEvent) => { event.preventDefault(); cancellation.post(`/delivery-notes/${note.id}/cancel`, { preserveScroll: true }); };
    const sendEmail = (event: FormEvent) => { event.preventDefault(); email.post(`/delivery-notes/${note.id}/email`, { preserveScroll: true }); };
    return <SalesLayout><Head title={note.delivery_note_number ?? `Delivery Note draft #${note.id}`} />
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href="/delivery-notes" className="text-sm text-slate-500">← Delivery Notes</Link><h2 className="mt-2 text-xl font-semibold">{note.delivery_note_number ?? `Delivery Note draft #${note.id}`}</h2><p className="text-sm text-slate-500">Order <Link href={`/sales/orders/${note.sales_order.id}`} className="underline">{note.sales_order.order_number}</Link> · {note.store.code} · {note.store.name}</p></div>{note.status === 'draft' && can.issue && <button onClick={() => router.post(`/delivery-notes/${note.id}/issue`)} className="rounded bg-slate-900 px-4 py-2 text-white">Issue Delivery Note</button>}</div>
        <section className="mb-6 grid gap-4 rounded-lg bg-slate-50 p-5 md:grid-cols-3"><div>Delivery date<br /><strong>{note.delivery_date.slice(0, 10)}</strong></div><div>Status<br /><strong className="capitalize">{note.status}</strong></div><div>Issued<br /><strong>{note.issued_at ? `${note.issued_by?.name ?? 'Unknown'} · ${note.issued_at}` : 'Not issued'}</strong></div></section>
        <section className="mb-6 flex flex-wrap items-end gap-3 rounded-lg border p-5"><a href={`/delivery-notes/${note.id}/print`} target="_blank" rel="noreferrer" className="rounded border px-4 py-2">{note.status === 'draft' ? 'Print preview' : 'Print'}</a>{note.status === 'issued' && <><a href={`/delivery-notes/${note.id}/pdf`} target="_blank" rel="noreferrer" className="rounded border px-4 py-2">Open PDF</a><a href={`/delivery-notes/${note.id}/download`} className="rounded border px-4 py-2">Download PDF</a></>}{note.status === 'issued' && can.email && <form onSubmit={sendEmail} className="flex flex-wrap items-end gap-2"><label className="text-sm">Recipient email<input type="email" required value={email.data.email} onChange={e => email.setData('email', e.target.value)} className="mt-1 block rounded border px-3 py-2" /></label><button disabled={email.processing} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50">{email.processing ? 'Sending…' : 'Email PDF'}</button>{email.errors.email && <span className="text-sm text-red-600">{email.errors.email}</span>}</form>}</section>
        {note.status === 'draft' && can.updateDraft && <form onSubmit={update} className="mb-6 grid gap-3 rounded-lg border p-5 md:grid-cols-2"><h3 className="font-semibold md:col-span-2">Draft recipient information</h3><label className="text-sm">Delivery date<input type="date" readOnly={!can.backdate} value={form.data.delivery_date} onChange={(e) => form.setData('delivery_date', e.target.value)} className="mt-1 w-full rounded border px-3 py-2 read-only:bg-slate-100" /></label><label className="text-sm">Recipient name<input value={form.data.recipient_name} onChange={(e) => form.setData('recipient_name', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Company<input value={form.data.recipient_company} onChange={(e) => form.setData('recipient_company', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Phone<input value={form.data.recipient_phone} onChange={(e) => form.setData('recipient_phone', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm md:col-span-2">Delivery address<textarea value={form.data.delivery_address} onChange={(e) => form.setData('delivery_address', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm md:col-span-2">Notes<textarea value={form.data.notes} onChange={(e) => form.setData('notes', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label>{Object.values(form.errors).map((error) => error && <p key={error} className="text-sm text-red-600 md:col-span-2">{error}</p>)}<button disabled={form.processing} className="w-fit rounded border px-4 py-2">Save draft</button></form>}
        {note.status !== 'draft' && <section className="mb-6 rounded-lg border p-5"><h3 className="font-semibold">Recipient snapshot</h3><p className="mt-2">{note.recipient_company ?? note.recipient_name ?? 'Walk-in'}</p><p>{note.recipient_phone}</p><p className="whitespace-pre-wrap">{note.delivery_address}</p></section>}
        <div className="mb-6 overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Item</th><th className="p-3">Reference</th><th className="p-3 text-right">Delivered quantity</th></tr></thead><tbody>{note.lines.map((line) => <tr key={line.id} className="border-t"><td className="p-3"><strong>{line.product_name ?? line.description}</strong><br /><span className="text-slate-500">{line.variant_name} {line.sku}</span></td><td className="p-3">{line.reference}</td><td className="p-3 text-right">{line.quantity} {line.unit_label}</td></tr>)}</tbody></table></div>
        {note.status === 'draft' && can.updateDraft && <form onSubmit={cancel} className="max-w-xl space-y-3 rounded-lg border border-red-200 p-5"><h3 className="font-semibold text-red-800">Cancel draft</h3><textarea value={cancellation.data.reason} onChange={(e) => cancellation.setData('reason', e.target.value)} placeholder="Reason (optional)" className="w-full rounded border px-3 py-2" /><button className="rounded border border-red-300 px-4 py-2 text-red-800">Cancel draft</button></form>}
        {note.status === 'cancelled' && <p className="rounded-lg bg-amber-50 p-5">Cancelled draft: {note.cancellation_reason ?? 'No reason supplied'}</p>}
    </SalesLayout>;
}
