import ProductImage from '@/components/catalog/ProductImage';
import { Button, ButtonLink } from '@/components/ui/Button';
import PageHeader from '@/components/ui/PageHeader';
import StatusBadge from '@/components/ui/StatusBadge';
import CatalogLayout from '@/layouts/CatalogLayout';
import { formatMoney, formatQuantity } from '@/utils/format';
import { Head, router } from '@inertiajs/react';

type Variant = { id: number; label: string | null; sku: string | null; reference: string | null; barcode: string | null; regular_sale_price: string; promotional_sale_price: string | null; default_sale_price: string; status: string; tax_rate: { name: string; rate: string } | null };
type Product = { id: number; name: string; description: string | null; image_url: string | null; status: string; brand: { name: string } | null; default_category: { name: string } | null; default_unit: { name: string; symbol: string } | null; variants: Variant[] };
type Stock = { variants: Array<{ id: number; label: string | null; sku: string; available_total: string; warehouses: Array<{ warehouse: { id: number; name: string; code: string }; on_hand: string; reserved: string; available: string }> }> } | null;

export default function ProductShow({ product, stock, can }: { product: Product; stock: Stock; can: { create: boolean; update: boolean; archive: boolean; stock: boolean; transfer: boolean } }) {
    const first = product.variants[0];
    return <CatalogLayout>
        <Head title={product.name} />
        <PageHeader title={product.name} description={product.description ?? 'Produit du catalogue'} actions={<>{can.create && <ButtonLink href="/catalog/products/create" variant="secondary">Ajouter un autre produit</ButtonLink>}{can.update && <ButtonLink href={`/catalog/products/${product.id}/edit`} variant="secondary">Modifier</ButtonLink>}{can.stock && <ButtonLink href={`/inventory/stock?search=${encodeURIComponent(first?.sku ?? product.name)}`}>Voir le stock</ButtonLink>}</>} />
        <section className="grid gap-6 rounded-2xl border bg-white p-6 lg:grid-cols-[minmax(260px,320px)_1fr]">
            <div className="flex items-center justify-center rounded-2xl bg-slate-50 p-4">
                <ProductImage name={product.name} imageUrl={product.image_url} className="h-64 w-full max-w-[18rem]" textClassName="text-slate-400 text-4xl" />
            </div>
            <div><div className="flex items-center gap-3"><h2 className="text-lg font-semibold">Identité produit</h2><StatusBadge status={product.status} /></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 xl:grid-cols-3"><div><dt className="text-slate-500">Marque</dt><dd className="font-medium">{product.brand?.name ?? 'Sans marque'}</dd></div><div><dt className="text-slate-500">SKU</dt><dd className="font-medium">{first?.sku ?? 'Non renseigné'}</dd></div><div><dt className="text-slate-500">Référence</dt><dd>{first?.reference ?? 'Non renseignée'}</dd></div><div><dt className="text-slate-500">Code-barres</dt><dd>{first?.barcode ?? '—'}</dd></div><div><dt className="text-slate-500">Catégorie</dt><dd>{product.default_category?.name ?? '—'}</dd></div><div><dt className="text-slate-500">Prix</dt><dd className="font-semibold">{first?.default_sale_price ? formatMoney(first.default_sale_price) : '—'}</dd></div><div><dt className="text-slate-500">Prix régulier</dt><dd>{first?.regular_sale_price ? formatMoney(first.regular_sale_price) : '—'}</dd></div><div><dt className="text-slate-500">Prix promotionnel</dt><dd>{first?.promotional_sale_price ? formatMoney(first.promotional_sale_price) : '—'}</dd></div><div><dt className="text-slate-500">Stock disponible</dt><dd className="font-medium">{stock?.variants?.[0] ? formatQuantity(stock.variants[0].available_total) : '—'}</dd></div></dl></div>
        </section>
        {can.stock && stock && <section className="mt-8 rounded-2xl border bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Disponibilité</h2><p className="mt-1 text-sm text-slate-600">Disponibilité par emplacement pour ce produit.</p></div><div className="flex flex-wrap gap-2">{can.update && <ButtonLink href={`/catalog/products/${product.id}/edit`} variant="secondary">Modifier</ButtonLink>}{can.transfer && first && <ButtonLink href={`/inventory/transfers/create?variant_id=${first.id}`}>Transférer</ButtonLink>}{can.stock && <ButtonLink href={`/inventory/stock?search=${encodeURIComponent(first?.sku ?? product.name)}`} variant="secondary">Ajuster le stock</ButtonLink>}{can.stock && <ButtonLink href={`/inventory/movements?search=${encodeURIComponent(first?.sku ?? product.name)}`} variant="secondary">Historique</ButtonLink>}</div></div><div className="mt-5 space-y-6">{stock.variants.map(variant => <article key={variant.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{variant.label ?? 'Variante principale'}</p><p className="text-sm text-slate-500">{variant.sku ?? 'Sans SKU'}</p></div><div className="text-right"><p className="text-xs uppercase tracking-wide text-slate-400">Total disponible</p><p className="text-lg font-semibold">{formatQuantity(variant.available_total)}</p></div></div><div className="mt-4 space-y-2">{variant.warehouses.map(row => <div key={row.warehouse.id} className="flex justify-between gap-3 border-t border-slate-200 pt-2 text-sm"><span>{row.warehouse.name}</span><span className="font-medium">{formatQuantity(row.available)}</span></div>)}</div>{can.transfer && <div className="mt-4"><ButtonLink href={`/inventory/transfers/create?variant_id=${variant.id}`} variant="secondary">Transférer cette variante</ButtonLink></div>}</article>)}</div></section>}
        <section className="mt-8"><h2 className="mb-3 text-lg font-semibold">Variantes</h2><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Variante</th><th className="p-3">SKU</th><th className="p-3">Reference</th><th className="p-3">Code-barres</th><th className="p-3 text-right">Prix regulier</th><th className="p-3 text-right">Prix promo</th><th className="p-3 text-right">Prix effectif</th><th className="p-3">Taxe</th><th className="p-3">Statut</th></tr></thead><tbody>{product.variants.map(variant => <tr key={variant.id} className="border-t"><td className="p-3">{variant.label ?? 'Principale'}</td><td className="p-3 font-medium">{variant.sku}</td><td className="p-3">{variant.reference ?? '—'}</td><td className="p-3">{variant.barcode ?? '—'}</td><td className="p-3 text-right">{variant.regular_sale_price ? formatMoney(variant.regular_sale_price) : '—'}</td><td className="p-3 text-right">{variant.promotional_sale_price ? formatMoney(variant.promotional_sale_price) : '—'}</td><td className="p-3 text-right font-medium">{formatMoney(variant.default_sale_price)}</td><td className="p-3">{variant.tax_rate?.name ?? '—'}</td><td className="p-3"><StatusBadge status={variant.status} /></td></tr>)}</tbody></table></div></section>
        <div className="mt-8 flex flex-wrap gap-2"><ButtonLink href="/catalog/products" variant="secondary">Retour aux produits</ButtonLink>{can.archive && product.status === 'active' && <Button variant="danger" type="button" onClick={() => window.confirm('Archiver ce produit ? Il ne sera plus proposé dans les opérations actives.') && router.patch(`/catalog/products/${product.id}/archive`)}>Archiver</Button>}</div>
    </CatalogLayout>;
}
