import PaymentsLayout from '@/layouts/PaymentsLayout';
import { formatDate, formatDateTime, formatMoney } from '@/utils/format';
import { Head, Link, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Payment = { id: number; payment_number: string; method: string; status: string; amount: string; currency_code: string; payment_date: string; reference: string | null; external_reference: string | null; notes: string | null; reversal_reason: string | null; reversed_at: string | null; store: { name: string; code: string }; financial_account: { name: string; code: string; type: string }; received_by: { name: string }; reversed_by: { name: string } | null; allocations: { id: number; amount: string; sales_order: { id: number; order_number: string; customer_name: string | null; customer_company: string | null; total_incl_tax: string; currency_code: string } }[]; refunds: { id: number; refund_number: string; amount: string; refund_date: string; reason: string; refunded_by: { name: string } | null }[] };
type Props = { payment: Payment; can: { reverse: boolean } };

export default function PaymentShow({ payment, can }: Props) {
    const reversal = useForm({ reason: '' });
    const reverse = (event: FormEvent) => { event.preventDefault(); reversal.post(`/payments/${payment.id}/reverse`, { preserveScroll: true }); };
    return <PaymentsLayout><Head title={payment.payment_number} />
        <div className="mb-6"><Link href="/payments" className="text-sm text-slate-500">← Payment register</Link><h2 className="mt-2 text-xl font-semibold">{payment.payment_number}</h2></div>
        <section className="mb-6 grid gap-4 rounded-lg bg-slate-50 p-5 md:grid-cols-4"><div>Business date<br /><strong>{formatDate(payment.payment_date)}</strong></div><div>Status<br /><strong className="capitalize">{payment.status}</strong></div><div>Method<br /><strong className="capitalize">{payment.method.replaceAll('_', ' ')}</strong></div><div>Amount<br /><strong>{formatMoney(payment.amount, payment.currency_code)}</strong></div><div>Account<br /><strong>{payment.financial_account.code} · {payment.financial_account.name}</strong></div><div>Store<br /><strong>{payment.store.code} · {payment.store.name}</strong></div><div>Received by<br /><strong>{payment.received_by.name}</strong></div><div>Reference<br /><strong>{payment.reference ?? '—'}</strong></div></section>
        <section className="mb-6 rounded-lg border p-5"><h3 className="mb-3 font-semibold">Allocation</h3>{payment.allocations.map((allocation) => <div key={allocation.id} className="flex flex-wrap justify-between gap-3"><div><Link href={`/sales/orders/${allocation.sales_order.id}`} className="font-medium underline">{allocation.sales_order.order_number}</Link><br /><span className="text-sm text-slate-500">{allocation.sales_order.customer_name ?? allocation.sales_order.customer_company ?? 'Walk-in'}</span></div><strong>{formatMoney(allocation.amount, payment.currency_code)}</strong></div>)}</section>
        {payment.refunds.length > 0 && <section className="mb-6 rounded-lg border border-red-200 bg-red-50 p-5"><h3 className="mb-3 font-semibold text-red-900">Remboursements</h3>{payment.refunds.map((refund) => <div key={refund.id} className="flex flex-wrap justify-between gap-3 border-t border-red-100 py-2 first:border-0"><div><strong>{refund.refund_number}</strong><br /><span className="text-sm text-slate-600">{formatDate(refund.refund_date)} · {refund.reason} · {refund.refunded_by?.name ?? 'Utilisateur supprimé'}</span></div><strong className="text-red-800">− {formatMoney(refund.amount, payment.currency_code)}</strong></div>)}</section>}
        {(payment.external_reference || payment.notes) && <section className="mb-6 rounded-lg border p-5"><h3 className="mb-2 font-semibold">Details</h3>{payment.external_reference && <p>External reference: {payment.external_reference}</p>}{payment.notes && <p className="mt-2 whitespace-pre-wrap">{payment.notes}</p>}</section>}
        {payment.status === 'reversed' && <section className="rounded-lg border border-amber-200 bg-amber-50 p-5"><h3 className="font-semibold">Reversed</h3><p className="mt-2">{payment.reversal_reason}</p><p className="mt-1 text-sm text-slate-500">By {payment.reversed_by?.name ?? 'Unknown'}{payment.reversed_at ? ` on ${formatDateTime(payment.reversed_at)}` : ''}</p></section>}
        {payment.status === 'posted' && can.reverse && <form onSubmit={reverse} className="max-w-xl space-y-3 rounded-lg border border-red-200 p-5"><h3 className="font-semibold text-red-800">Reverse payment</h3><p className="text-sm text-slate-600">Reversal preserves the original record and recalculates the order balance.</p><textarea required maxLength={2000} value={reversal.data.reason} onChange={(event) => reversal.setData('reason', event.target.value)} placeholder="Reversal reason" className="w-full rounded border px-3 py-2" />{reversal.errors.reason && <p className="text-sm text-red-600">{reversal.errors.reason}</p>}<button disabled={reversal.processing} className="rounded border border-red-300 px-4 py-2 text-red-800 disabled:opacity-50">Reverse payment</button></form>}
    </PaymentsLayout>;
}
