<?php

return [
    'currency_code' => 'MAD',

    'permissions' => [
        'organizations.view' => 'View organizations',
        'organizations.update' => 'Update organizations',
        'organizations.delete' => 'Delete organizations',
        'settings.update' => 'Update organization settings',
        'stores.view' => 'View stores',
        'stores.create' => 'Create stores',
        'stores.update' => 'Update stores',
        'stores.delete' => 'Delete stores',
        'members.view' => 'View organization members',
        'members.create' => 'Add organization members',
        'members.update' => 'Change organization member roles',
        'members.delete' => 'Remove organization members',
        'store-memberships.manage' => 'Manage store memberships',
        'roles.view' => 'View roles',
        'roles.create' => 'Create roles',
        'roles.update' => 'Update roles',
        'roles.delete' => 'Delete roles',
        'roles.assign-permissions' => 'Assign permissions to roles',
        'catalog.view' => 'Access the catalog',
        'products.view' => 'View products',
        'products.create' => 'Create products',
        'products.update' => 'Update products',
        'products.archive' => 'Archive products',
        'categories.view' => 'View categories',
        'categories.manage' => 'Manage categories',
        'brands.view' => 'View brands',
        'brands.manage' => 'Manage brands',
        'units.view' => 'View units of measure',
        'units.manage' => 'Manage units of measure',
        'tax_rates.view' => 'View tax rates',
        'tax_rates.manage' => 'Manage tax rates',
        'warehouses.view' => 'View warehouses',
        'warehouses.create' => 'Create warehouses',
        'warehouses.update' => 'Update warehouses',
        'inventory.view' => 'View inventory',
        'inventory.opening' => 'Add opening stock',
        'inventory.adjust' => 'Adjust inventory',
        'inventory.reserve' => 'Reserve inventory',
        'inventory.release' => 'Release inventory reservations',
        'inventory.consume' => 'Consume inventory reservations',
        'customers.view' => 'View customers',
        'customers.create' => 'Create customers',
        'customers.update' => 'Update customers',
        'sales_orders.view' => 'View sales orders',
        'sales_orders.create' => 'Create sales orders',
        'sales_orders.update' => 'Update draft sales orders',
        'sales_orders.confirm' => 'Confirm sales orders',
        'sales_orders.cancel' => 'Cancel sales orders',
        'sales_orders.fulfill' => 'Fulfill sales orders',
        'sales_orders.override_price' => 'Override catalog sale prices',
        'sales_orders.apply_discount' => 'Apply sales order line discounts',
        'pos.access' => 'Access the point of sale',
    ],

    'default_roles' => [
        'owner' => [
            'name' => 'Owner',
            'permissions' => '*',
        ],
        'admin' => [
            'name' => 'Admin',
            'permissions' => [
                'organizations.view',
                'organizations.update',
                'settings.update',
                'stores.view',
                'stores.create',
                'stores.update',
                'stores.delete',
                'members.view',
                'members.create',
                'members.update',
                'members.delete',
                'store-memberships.manage',
                'roles.view',
                'roles.create',
                'roles.update',
                'roles.delete',
                'roles.assign-permissions',
                'catalog.view',
                'products.view',
                'products.create',
                'products.update',
                'products.archive',
                'categories.view',
                'categories.manage',
                'brands.view',
                'brands.manage',
                'units.view',
                'units.manage',
                'tax_rates.view',
                'tax_rates.manage',
                'warehouses.view',
                'warehouses.create',
                'warehouses.update',
                'inventory.view',
                'inventory.opening',
                'inventory.adjust',
                'inventory.reserve',
                'inventory.release',
                'inventory.consume',
                'customers.view',
                'customers.create',
                'customers.update',
                'sales_orders.view',
                'sales_orders.create',
                'sales_orders.update',
                'sales_orders.confirm',
                'sales_orders.cancel',
                'sales_orders.fulfill',
                'sales_orders.override_price',
                'sales_orders.apply_discount',
                'pos.access',
            ],
        ],
        'sales-employee' => [
            'name' => 'Sales Employee',
            'permissions' => [
                'organizations.view',
                'stores.view',
                'catalog.view',
                'products.view',
                'categories.view',
                'brands.view',
                'units.view',
                'tax_rates.view',
                'inventory.view',
                'customers.view',
                'customers.create',
                'customers.update',
                'sales_orders.view',
                'sales_orders.create',
                'sales_orders.update',
                'sales_orders.confirm',
                'sales_orders.fulfill',
                'pos.access',
            ],
        ],
    ],
];
