<?php

return [
    'currency_code' => 'MAD',

    'permissions' => [
        'organizations.view' => 'View organizations',
        'organizations.update' => 'Update organizations',
        'organizations.delete' => 'Delete organizations',
        'settings.update' => 'Update organization settings',
        'stores.view' => 'View stores',
        'stores.create' => 'Create stores',
        'stores.update' => 'Update stores',
        'stores.delete' => 'Delete stores',
        'members.view' => 'View organization members',
        'members.create' => 'Add organization members',
        'members.update' => 'Change organization member roles',
        'members.delete' => 'Remove organization members',
        'store-memberships.manage' => 'Manage store memberships',
        'roles.view' => 'View roles',
        'roles.create' => 'Create roles',
        'roles.update' => 'Update roles',
        'roles.delete' => 'Delete roles',
        'roles.assign-permissions' => 'Assign permissions to roles',
        'catalog.view' => 'Access the catalog',
        'products.view' => 'View products',
        'products.create' => 'Create products',
        'products.update' => 'Update products',
        'products.archive' => 'Archive products',
        'products.import' => 'Import products',
        'categories.view' => 'View categories',
        'categories.manage' => 'Manage categories',
        'brands.view' => 'View brands',
        'brands.manage' => 'Manage brands',
        'units.view' => 'View units of measure',
        'units.manage' => 'Manage units of measure',
        'tax_rates.view' => 'View tax rates',
        'tax_rates.manage' => 'Manage tax rates',
        'warehouses.view' => 'View warehouses',
        'warehouses.create' => 'Create warehouses',
        'warehouses.update' => 'Update warehouses',
        'inventory.view' => 'View inventory',
        'inventory.opening' => 'Add opening stock',
        'inventory.adjust' => 'Adjust inventory',
        'inventory.transfer' => 'Transfer inventory',
        'inventory.reserve' => 'Reserve inventory',
        'inventory.release' => 'Release inventory reservations',
        'inventory.consume' => 'Consume inventory reservations',
        'inventory.transfer_requests.view' => 'View internal transfer requests',
        'inventory.transfer_requests.manage' => 'Prepare, ship, cancel transfer requests and configure replenishment',
        'inventory.transfer_requests.receive' => 'Receive internal transfer requests',
        'suppliers.view' => 'View suppliers',
        'suppliers.manage' => 'Create and update suppliers',
        'procurement.view' => 'View supplier procurements (special orders)',
        'procurement.manage' => 'Raise supplier procurements, record availability, order and cancel',
        'procurement.receive' => 'Confirm the physical receipt of supplier-procured goods',
        'customers.view' => 'View customers',
        'customers.create' => 'Create customers',
        'customers.update' => 'Update customers',
        'sales_orders.view' => 'View sales orders',
        'sales_orders.create' => 'Create sales orders',
        'sales_orders.update' => 'Update draft sales orders',
        'sales_orders.confirm' => 'Confirm sales orders',
        'sales_orders.cancel' => 'Cancel sales orders',
        'sales_orders.fulfill' => 'Fulfill sales orders',
        'sales_orders.override_price' => 'Override catalog sale prices',
        'sales_orders.apply_discount' => 'Apply sales order line discounts',
        'pos.access' => 'Access the point of sale',
        'financial_accounts.view' => 'View financial accounts',
        'financial_accounts.create' => 'Create financial accounts',
        'financial_accounts.update' => 'Update financial accounts',
        'payments.view' => 'View payments',
        'payments.create' => 'Record payments',
        'payments.reverse' => 'Reverse posted payments',
        'payments.backdate' => 'Record payments on a date other than today',
        'invoices.view' => 'View invoices',
        'invoices.create' => 'Create invoice drafts',
        'invoices.update_draft' => 'Update invoice drafts',
        'invoices.issue' => 'Issue invoices',
        'invoices.backdate' => 'Use an invoice date other than today',
        'invoices.email' => 'Email issued invoices',
        'quotations.view' => 'View quotations (devis)',
        'quotations.create' => 'Create quotation drafts',
        'quotations.update' => 'Update quotation drafts',
        'quotations.issue' => 'Issue quotations',
        'quotations.accept' => 'Mark quotations accepted or rejected',
        'quotations.convert' => 'Convert a quotation into a sales order',
        'quotations.email' => 'Email issued quotations',
        'non_stock_items.manage' => 'Manage the non-stock (external) article library',
        'delivery_notes.view' => 'View delivery notes',
        'delivery_notes.create' => 'Create delivery note drafts',
        'delivery_notes.update_draft' => 'Update delivery note drafts',
        'delivery_notes.issue' => 'Issue delivery notes',
        'delivery_notes.backdate' => 'Use a delivery date other than today',
        'delivery_notes.email' => 'Email issued delivery notes',
        'integrations.view' => 'View external integrations',
        'integrations.manage' => 'Configure external integrations and credentials',
        'integrations.sync' => 'Run external integration synchronizations',
    ],

    'default_roles' => [
        'owner' => [
            'name' => 'Owner',
            'permissions' => '*',
        ],
        'admin' => [
            'name' => 'Admin',
            'permissions' => [
                'organizations.view',
                'organizations.update',
                'settings.update',
                'stores.view',
                'stores.create',
                'stores.update',
                'stores.delete',
                'members.view',
                'members.create',
                'members.update',
                'members.delete',
                'store-memberships.manage',
                'roles.view',
                'roles.create',
                'roles.update',
                'roles.delete',
                'roles.assign-permissions',
                'catalog.view',
                'products.view',
                'products.create',
                'products.update',
                'products.archive',
                'products.import',
                'categories.view',
                'categories.manage',
                'brands.view',
                'brands.manage',
                'units.view',
                'units.manage',
                'tax_rates.view',
                'tax_rates.manage',
                'warehouses.view',
                'warehouses.create',
                'warehouses.update',
                'inventory.view',
                'inventory.opening',
                'inventory.adjust',
                'inventory.transfer',
                'inventory.reserve',
                'inventory.release',
                'inventory.consume',
                'inventory.transfer_requests.view',
                'inventory.transfer_requests.manage',
                'inventory.transfer_requests.receive',
                'suppliers.view',
                'suppliers.manage',
                'procurement.view',
                'procurement.manage',
                'procurement.receive',
                'customers.view',
                'customers.create',
                'customers.update',
                'sales_orders.view',
                'sales_orders.create',
                'sales_orders.update',
                'sales_orders.confirm',
                'sales_orders.cancel',
                'sales_orders.fulfill',
                'sales_orders.override_price',
                'sales_orders.apply_discount',
                'pos.access',
                'financial_accounts.view',
                'financial_accounts.create',
                'financial_accounts.update',
                'payments.view',
                'payments.create',
                'payments.reverse',
                'payments.backdate',
                'invoices.view',
                'invoices.create',
                'invoices.update_draft',
                'invoices.issue',
                'invoices.backdate',
                'invoices.email',
                'quotations.view',
                'quotations.create',
                'quotations.update',
                'quotations.issue',
                'quotations.accept',
                'quotations.convert',
                'quotations.email',
                'non_stock_items.manage',
                'delivery_notes.view',
                'delivery_notes.create',
                'delivery_notes.update_draft',
                'delivery_notes.issue',
                'delivery_notes.backdate',
                'delivery_notes.email',
                'integrations.view',
                'integrations.manage',
                'integrations.sync',
            ],
        ],
        'sales-employee' => [
            'name' => 'Sales Employee',
            'permissions' => [
                'organizations.view',
                'stores.view',
                'catalog.view',
                'products.view',
                'categories.view',
                'brands.view',
                'units.view',
                'tax_rates.view',
                'inventory.view',
                'inventory.transfer_requests.view',
                'inventory.transfer_requests.receive',
                'suppliers.view',
                'suppliers.manage',
                'procurement.view',
                'procurement.manage',
                'procurement.receive',
                'customers.view',
                'customers.create',
                'customers.update',
                'sales_orders.view',
                'sales_orders.create',
                'sales_orders.update',
                'sales_orders.confirm',
                'sales_orders.fulfill',
                'pos.access',
                'payments.view',
                'payments.create',
                'invoices.view',
                'invoices.create',
                'invoices.update_draft',
                'invoices.issue',
                'invoices.email',
                'quotations.view',
                'quotations.create',
                'quotations.update',
                'quotations.issue',
                'quotations.accept',
                'quotations.convert',
                'quotations.email',
                'non_stock_items.manage',
                'delivery_notes.view',
                'delivery_notes.create',
                'delivery_notes.update_draft',
                'delivery_notes.issue',
                'delivery_notes.email',
            ],
        ],
    ],
];
