import { Link } from '@inertiajs/react';
import { formatMoney } from '@/utils/format';

type CompletedOrder = { id: number; order_number: string; customer_name: string | null; total_incl_tax: string; currency_code: string; fulfillment_status: string; payment_status: string; paid: string; remaining: string; payments: { id: number; payment_number: string; method: string; amount: string; reference: string | null; account: { name: string; code: string; type: string }; cash_received: string | null; change: string | null }[] };

export default function PosCheckoutSummary({ order, onNewSale }: { order: CompletedOrder; onNewSale: () => void }) {
    return <section className="rounded-xl border border-emerald-200 bg-emerald-50 p-5 print:border-0 print:bg-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><strong className="text-lg text-emerald-950">Sale completed — {order.order_number}</strong><p className="text-sm text-emerald-800">{order.customer_name ?? 'Walk-in customer'} · Payment {order.payment_status.toUpperCase()} · Fulfillment {order.fulfillment_status.toUpperCase()}</p></div><div className="flex gap-2 print:hidden"><button type="button" onClick={onNewSale} className="rounded bg-slate-900 px-4 py-2 text-white">New Sale</button><button type="button" onClick={() => window.print()} className="rounded border border-emerald-300 px-4 py-2">Print summary</button><Link href={`/sales/orders/${order.id}`} className="rounded border border-emerald-300 px-4 py-2">View Order</Link></div></div>
        <dl className="mt-4 grid grid-cols-3 gap-3 rounded bg-white/70 p-4 text-sm"><div><dt>Total</dt><dd className="font-semibold">{formatMoney(order.total_incl_tax, order.currency_code)}</dd></div><div><dt>Paid</dt><dd className="font-semibold">{formatMoney(order.paid, order.currency_code)}</dd></div><div><dt>Remaining</dt><dd className="font-semibold">{formatMoney(order.remaining, order.currency_code)}</dd></div></dl>
        <div className="mt-4 space-y-2">{order.payments.map((payment) => <div key={payment.id} className="flex flex-wrap justify-between gap-3 rounded border border-emerald-100 bg-white p-3 text-sm"><span><strong className="capitalize">{payment.method.replaceAll('_', ' ')}</strong> · {payment.account.code} / {payment.account.name}{payment.reference ? ` · ${payment.reference}` : ''}{payment.cash_received && <><br /><span className="text-slate-500">Cash received {formatMoney(payment.cash_received, order.currency_code)} · Change {formatMoney(payment.change, order.currency_code)}</span></>}</span><strong>{formatMoney(payment.amount, order.currency_code)}</strong></div>)}</div>
        <p className="mt-4 text-xs text-slate-500">Operational checkout summary — not an invoice.</p>
    </section>;
}
