import { Button } from '@/components/ui/Button';
import SalesLayout from '@/layouts/SalesLayout';
import { formatDateTime as formatDate, formatMoney, formatQuantity } from '@/utils/format';
import { Head, Link, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Line={id:number;product_name:string;variant_name:string|null;sku:string|null;reference:string|null;unit_label:string|null;quantity:string;unit_price_incl_tax:string;total_incl_tax:string;already_returned:string;returnable:string};
type Policy={enabled:boolean;within_policy:boolean;deadline:string|null;fulfilled_at:string|null;allow_partial:boolean;allow_full:boolean;manager_override_allowed:boolean;require_reason:boolean;default_disposition:'restock'|'damaged'};
type Props={order:{id:number;order_number:string;customer_name:string|null;fulfilled_at:string;currency_code:string;invoices:{invoice_number:string}[]};policy:Policy;lines:Line[];canOverride:boolean;submitUrl:string};
export default function ReturnCreate({order,policy,lines,canOverride,submitUrl}:Props){const form=useForm({client_operation_id:crypto.randomUUID(),reason:'',disposition:policy.default_disposition,override_policy:false,override_reason:'',lines:lines.map(line=>({sales_order_line_id:line.id,quantity:''}))});
 const setQty=(id:number,value:string)=>form.setData('lines',form.data.lines.map(line=>line.sales_order_line_id===id?{...line,quantity:value}:line));
 const all=()=>form.setData('lines',lines.map(line=>({sales_order_line_id:line.id,quantity:Number(line.returnable)>0?line.returnable:''})));
 const submit=(e:FormEvent)=>{e.preventDefault();form.transform(data=>({...data,lines:data.lines.filter(line=>Number(line.quantity)>0)}));form.post(submitUrl)};
 const blocked=!policy.enabled||(!policy.within_policy&&!(canOverride&&policy.manager_override_allowed&&form.data.override_policy));
 return <SalesLayout><Head title={`Retour ${order.order_number}`}/><div className="mx-auto max-w-5xl space-y-6"><header><Link href={`/sales/orders/${order.id}`} className="text-sm text-ink-muted">← {order.order_number}</Link><h1 className="text-2xl font-semibold">Retourner des articles</h1><p className="text-sm text-ink-muted">{order.customer_name||'Client comptoir'} · Facture {order.invoices.map(i=>i.invoice_number).join(', ')||'non émise'}</p></header>
 <section className={`rounded-card border p-4 ${policy.within_policy?'border-success/30 bg-success/5':'border-danger/30 bg-danger/5'}`}><p className="font-medium">{policy.within_policy?'✓ Retour autorisé':policy.enabled?'⛔ Délai de retour dépassé':'⛔ Les retours sont désactivés'}</p><p className="text-sm">Livrée le : {formatDate(order.fulfilled_at)} · Retour autorisé jusqu’au : {policy.deadline?formatDate(policy.deadline):'—'}</p>{!policy.within_policy&&policy.enabled&&canOverride&&policy.manager_override_allowed&&<div className="mt-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.data.override_policy} onChange={e=>form.setData('override_policy',e.target.checked)}/>Forcer l’acceptation</label>{form.data.override_policy&&<textarea value={form.data.override_reason} onChange={e=>form.setData('override_reason',e.target.value)} placeholder="Motif obligatoire du dépassement" className="mt-2 w-full rounded-field border border-line-strong p-2 text-sm"/>}</div>}</section>
 <form onSubmit={submit} className="space-y-5"><section className="overflow-x-auto rounded-card border border-line bg-surface"><div className="flex justify-between p-4"><h2 className="font-semibold">Articles livrés</h2><button type="button" onClick={all} className="text-sm font-medium text-primary">Tout retourner</button></div><table className="w-full text-sm"><thead className="bg-raised text-left text-xs uppercase text-ink-muted"><tr><th className="p-3">Article</th><th className="p-3">Acheté</th><th className="p-3">Déjà retourné</th><th className="p-3">Retournable</th><th className="p-3">Prix historique</th><th className="p-3">Quantité</th></tr></thead><tbody>{lines.map((line,index)=><tr key={line.id} className="border-t border-line"><td className="p-3"><strong>{line.reference||line.sku||'—'}</strong><span className="block">{line.product_name}{line.variant_name?` — ${line.variant_name}`:''}</span></td><td className="p-3">{formatQuantity(line.quantity)}</td><td className="p-3">{formatQuantity(line.already_returned)}</td><td className="p-3">{formatQuantity(line.returnable)}</td><td className="p-3">{formatMoney(line.unit_price_incl_tax,order.currency_code)}</td><td className="p-3"><input type="number" min="0" max={line.returnable} step="0.0001" value={form.data.lines[index]?.quantity??''} onChange={e=>setQty(line.id,e.target.value)} disabled={Number(line.returnable)<=0} className="w-28 rounded-field border border-line-strong px-2 py-1.5"/></td></tr>)}</tbody></table></section>
 <section className="grid gap-4 rounded-card border border-line bg-surface p-5 sm:grid-cols-2"><label className="text-sm font-medium">Disposition des articles<select value={form.data.disposition} onChange={e=>form.setData('disposition',e.target.value as 'restock'|'damaged')} className="mt-1 w-full rounded-field border border-line-strong px-3 py-2"><option value="restock">Vendable — remettre en stock à la réception</option><option value="damaged">Endommagé / non vendable</option></select></label><label className="text-sm font-medium">Motif<textarea value={form.data.reason} onChange={e=>form.setData('reason',e.target.value)} className="mt-1 w-full rounded-field border border-line-strong p-2" rows={3}/></label><div className="sm:col-span-2">{Object.values(form.errors).map(error=>error&&<p key={error} className="text-sm text-danger">{error}</p>)}<Button type="submit" disabled={blocked} loading={form.processing}>Créer le retour</Button><p className="mt-2 text-xs text-ink-muted">Aucun stock ne change avant la réception physique.</p></div></section></form></div></SalesLayout>}
