import SalesLayout from '@/layouts/SalesLayout';
import { Head, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Customer = { id: number; display_name: string; company_name: string | null };
export default function CreateOrder({ customers, currencyCode }: { customers: Customer[]; currencyCode: string }) {
    const form = useForm({ customer_id: null as number | null, sale_date: new Date().toISOString().slice(0, 10), currency_code: currencyCode, notes: '' });
    const submit = (event: FormEvent) => { event.preventDefault(); form.post('/sales/orders'); };
    return <SalesLayout><Head title="Create Sales Order" /><form onSubmit={submit} className="mx-auto max-w-2xl space-y-4"><h2 className="text-xl font-semibold">Create Sales Order</h2><div className="space-y-4 rounded-lg border p-5"><label>Customer<select value={form.data.customer_id ?? ''} onChange={(e) => form.setData('customer_id', e.target.value ? Number(e.target.value) : null)} className="mt-1 w-full rounded border px-3 py-2"><option value="">Walk-in / no customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.display_name}{customer.company_name ? ` — ${customer.company_name}` : ''}</option>)}</select></label><label>Sale date<input type="date" required value={form.data.sale_date} onChange={(e) => form.setData('sale_date', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label>Currency<input maxLength={3} required value={form.data.currency_code} onChange={(e) => form.setData('currency_code', e.target.value.toUpperCase())} className="mt-1 w-full rounded border px-3 py-2" /></label><label>Notes<textarea value={form.data.notes} onChange={(e) => form.setData('notes', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label></div>{Object.values(form.errors).map((error, index) => <p key={index} className="text-sm text-red-600">{error}</p>)}<button disabled={form.processing} className="rounded bg-slate-900 px-4 py-2 text-white">Create draft</button></form></SalesLayout>;
}
