import SalesLayout from '@/layouts/SalesLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Line = { id: number; product_name: string; variant_name: string | null; sku: string | null; quantity: string; unit_price_excl_tax: string; discount_amount: string; tax_amount: string; total_incl_tax: string; allocations: { warehouse: { name: string }; inventory_reservation: { status: string } | null }[] };
type Order = { id: number; order_number: string; customer_name: string | null; customer_company: string | null; customer_email: string | null; customer_phone: string | null; sale_date: string; ordered_at: string; currency_code: string; status: string; fulfillment_status: string; payment_status: string; subtotal_excl_tax: string; discount_total: string; tax_total: string; total_incl_tax: string; notes: string | null; store: { name: string; code: string }; lines: Line[] };
type Props = { order: Order; can: { update: boolean; confirm: boolean; cancel: boolean; fulfill: boolean } };

export default function ShowOrder({ order, can }: Props) {
    const cancellation = useForm({ reason: '' });
    const cancel = (event: FormEvent) => { event.preventDefault(); cancellation.post(`/sales/orders/${order.id}/cancel`, { preserveScroll: true }); };
    return <SalesLayout><Head title={order.order_number} /><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{order.order_number}</h2><p className="text-sm text-slate-500">{order.store.name} · Sale date {order.sale_date.slice(0, 10)}</p></div><div className="flex gap-2">{order.status === 'draft' && can.update && <Link href={`/sales/orders/${order.id}/edit`} className="rounded border px-4 py-2">Edit</Link>}{order.status === 'draft' && can.confirm && <button onClick={() => router.post(`/sales/orders/${order.id}/confirm`)} className="rounded bg-slate-900 px-4 py-2 text-white">Confirm</button>}{order.status === 'confirmed' && order.fulfillment_status === 'unfulfilled' && can.fulfill && <button onClick={() => router.post(`/sales/orders/${order.id}/fulfill`)} className="rounded bg-slate-900 px-4 py-2 text-white">Fulfill</button>}</div></div>
        <div className="mb-6 grid gap-4 rounded-lg bg-slate-50 p-5 md:grid-cols-4"><div>Customer<br /><strong>{order.customer_name ?? 'Walk-in'}</strong><br /><span className="text-sm text-slate-500">{order.customer_company}</span></div><div>Order status<br /><strong className="capitalize">{order.status}</strong></div><div>Fulfillment<br /><strong>{order.fulfillment_status.replaceAll('_', ' ')}</strong></div><div>Payment<br /><strong>{order.payment_status.replaceAll('_', ' ')}</strong></div></div>
        <div className="mb-6 overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Item</th><th className="p-3">Warehouse / reservation</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Price</th><th className="p-3 text-right">Discount</th><th className="p-3 text-right">Tax</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{order.lines.map((line) => <tr key={line.id} className="border-t"><td className="p-3"><strong>{line.product_name}</strong><br />{line.variant_name ?? ''} {line.sku ?? ''}</td><td className="p-3">{line.allocations.map((allocation) => <div key={allocation.warehouse.name}>{allocation.warehouse.name} · {allocation.inventory_reservation?.status ?? 'draft'}</div>)}</td><td className="p-3 text-right">{line.quantity}</td><td className="p-3 text-right">{line.unit_price_excl_tax}</td><td className="p-3 text-right">{line.discount_amount}</td><td className="p-3 text-right">{line.tax_amount}</td><td className="p-3 text-right">{line.total_incl_tax}</td></tr>)}</tbody></table></div>
        <div className="ml-auto mb-8 grid max-w-2xl grid-cols-4 gap-3 text-right"><div>Subtotal<br /><strong>{order.subtotal_excl_tax}</strong></div><div>Discount<br /><strong>{order.discount_total}</strong></div><div>Tax<br /><strong>{order.tax_total}</strong></div><div>Total<br /><strong>{order.total_incl_tax} {order.currency_code}</strong></div></div>
        {can.cancel && order.status !== 'cancelled' && order.fulfillment_status === 'unfulfilled' && <form onSubmit={cancel} className="max-w-xl space-y-3 rounded-lg border border-red-200 p-5"><h3 className="font-semibold text-red-800">Cancel order</h3><textarea required={order.status === 'confirmed'} value={cancellation.data.reason} onChange={(e) => cancellation.setData('reason', e.target.value)} placeholder={order.status === 'confirmed' ? 'Cancellation reason required' : 'Reason (optional for draft)'} className="w-full rounded border px-3 py-2" /><button className="rounded border border-red-300 px-4 py-2 text-red-800">Cancel order</button></form>}
    </SalesLayout>;
}
