import SalesLayout from '@/layouts/SalesLayout';
import { Head, Link, router, useForm } from '@inertiajs/react';
import type { FormEvent } from 'react';

type Line = { id: number; product_name: string; variant_name: string | null; sku: string | null; quantity: string; unit_price_excl_tax: string; discount_amount: string; tax_amount: string; total_incl_tax: string; allocations: { warehouse: { name: string }; inventory_reservation: { status: string } | null }[] };
type Order = { id: number; order_number: string; customer_name: string | null; customer_company: string | null; sale_date: string; currency_code: string; status: string; fulfillment_status: string; payment_status: string; subtotal_excl_tax: string; discount_total: string; tax_total: string; total_incl_tax: string; store: { name: string }; lines: Line[] };
type Account = { id: number; name: string; code: string; type: string; currency_code: string };
type Payment = { id: number; payment_number: string; method: string; status: string; amount: string; allocated_amount: string; payment_date: string; reference: string | null; financial_account: Account; received_by: { name: string } };
type PaymentEntry = { method: string; financial_account_id: string; amount: string; payment_date: string; reference: string; external_reference: string; notes: string };
type Props = { order: Order; paymentSummary: { paid: string; remaining: string; status: string }; payments: Payment[]; financialAccounts: Account[]; documents: { invoices: { id: number; invoice_number: string | null; invoice_date: string; status: string; total_incl_tax: string }[]; deliveryNotes: { id: number; delivery_note_number: string | null; delivery_date: string; status: string }[] }; can: { update: boolean; confirm: boolean; cancel: boolean; fulfill: boolean; recordPayment: boolean; backdatePayment: boolean; createInvoice: boolean; createDeliveryNote: boolean } };
const today = () => {
    const date = new Date();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${date.getFullYear()}-${month}-${day}`;
};
const blankPayment = (remaining = ''): PaymentEntry => ({ method: 'cash', financial_account_id: '', amount: remaining, payment_date: today(), reference: '', external_reference: '', notes: '' });

export default function ShowOrder({ order, paymentSummary, payments, financialAccounts, documents, can }: Props) {
    const cancellation = useForm({ reason: '' });
    const paymentForm = useForm<{ client_operation_id: string; payments: PaymentEntry[] }>({ client_operation_id: crypto.randomUUID(), payments: [blankPayment(paymentSummary.remaining)] });
    const cancel = (event: FormEvent) => { event.preventDefault(); cancellation.post(`/sales/orders/${order.id}/cancel`, { preserveScroll: true }); };
    const recordPayments = (event: FormEvent) => { event.preventDefault(); paymentForm.post(`/sales/orders/${order.id}/payments`, { preserveScroll: true, onSuccess: () => paymentForm.setData({ client_operation_id: crypto.randomUUID(), payments: [blankPayment()] }) }); };
    const setEntry = (index: number, key: keyof PaymentEntry, value: string) => paymentForm.setData('payments', paymentForm.data.payments.map((entry, position) => position === index ? { ...entry, [key]: value } : entry));
    return <SalesLayout><Head title={order.order_number} />
        <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">{order.order_number}</h2><p className="text-sm text-slate-500">{order.store.name} · Sale date {order.sale_date.slice(0, 10)}</p></div><div className="flex flex-wrap gap-2">{order.status === 'draft' && can.update && <Link href={`/sales/orders/${order.id}/edit`} className="rounded border px-4 py-2">Edit</Link>}{order.status === 'draft' && can.confirm && <button onClick={() => router.post(`/sales/orders/${order.id}/confirm`)} className="rounded bg-slate-900 px-4 py-2 text-white">Confirm</button>}{order.status === 'confirmed' && order.fulfillment_status === 'unfulfilled' && can.fulfill && <button onClick={() => router.post(`/sales/orders/${order.id}/fulfill`)} className="rounded bg-slate-900 px-4 py-2 text-white">Fulfill</button>}{order.status === 'confirmed' && can.createInvoice && !documents.invoices.some((invoice) => invoice.status !== 'cancelled') && <button onClick={() => router.post(`/sales/orders/${order.id}/invoices`)} className="rounded border px-4 py-2">Create invoice</button>}{order.status === 'confirmed' && order.fulfillment_status === 'fulfilled' && can.createDeliveryNote && !documents.deliveryNotes.some((note) => note.status !== 'cancelled') && <button onClick={() => router.post(`/sales/orders/${order.id}/delivery-notes`)} className="rounded border px-4 py-2">Create delivery note</button>}</div></div>
        <div className="mb-6 grid gap-4 rounded-lg bg-slate-50 p-5 md:grid-cols-4"><div>Customer<br /><strong>{order.customer_name ?? 'Walk-in'}</strong><br /><span className="text-sm text-slate-500">{order.customer_company}</span></div><div>Order status<br /><strong className="capitalize">{order.status}</strong></div><div>Fulfillment<br /><strong>{order.fulfillment_status.replaceAll('_', ' ')}</strong></div><div>Payment<br /><strong>{paymentSummary.status.replaceAll('_', ' ')}</strong></div></div>
        <div className="mb-6 overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Item</th><th className="p-3">Warehouse / reservation</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Price</th><th className="p-3 text-right">Discount</th><th className="p-3 text-right">Tax</th><th className="p-3 text-right">Total</th></tr></thead><tbody>{order.lines.map((line) => <tr key={line.id} className="border-t"><td className="p-3"><strong>{line.product_name}</strong><br />{line.variant_name ?? ''} {line.sku ?? ''}</td><td className="p-3">{line.allocations.map((allocation) => <div key={allocation.warehouse.name}>{allocation.warehouse.name} · {allocation.inventory_reservation?.status ?? 'draft'}</div>)}</td><td className="p-3 text-right">{line.quantity}</td><td className="p-3 text-right">{line.unit_price_excl_tax}</td><td className="p-3 text-right">{line.discount_amount}</td><td className="p-3 text-right">{line.tax_amount}</td><td className="p-3 text-right">{line.total_incl_tax}</td></tr>)}</tbody></table></div>
        <div className="ml-auto mb-8 grid max-w-3xl grid-cols-3 gap-3 rounded-lg bg-slate-50 p-4 text-right"><div>Total<br /><strong>{order.total_incl_tax} {order.currency_code}</strong></div><div>Paid<br /><strong>{paymentSummary.paid} {order.currency_code}</strong></div><div>Remaining<br /><strong>{paymentSummary.remaining} {order.currency_code}</strong></div></div>
        <section className="mb-8"><h3 className="mb-3 font-semibold">Payment history</h3><div className="overflow-x-auto rounded-lg border"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Payment</th><th className="p-3">Date</th><th className="p-3">Method / account</th><th className="p-3">Status</th><th className="p-3 text-right">Allocated</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id} className="border-t"><td className="p-3"><Link href={`/payments/${payment.id}`} className="font-medium underline">{payment.payment_number}</Link><br /><span className="text-slate-500">{payment.reference}</span></td><td className="p-3">{payment.payment_date.slice(0, 10)}</td><td className="p-3 capitalize">{payment.method.replaceAll('_', ' ')}<br /><span className="text-slate-500">{payment.financial_account.name}</span></td><td className="p-3 capitalize">{payment.status}</td><td className="p-3 text-right">{payment.allocated_amount} {order.currency_code}</td></tr>)}{payments.length === 0 && <tr><td colSpan={5} className="p-6 text-center text-slate-500">No payments recorded.</td></tr>}</tbody></table></div></section>
        <section className="mb-8 grid gap-4 md:grid-cols-2"><div className="rounded-lg border p-5"><h3 className="mb-3 font-semibold">Invoices</h3>{documents.invoices.map((invoice) => <p key={invoice.id}><Link href={`/invoices/${invoice.id}`} className="underline">{invoice.invoice_number ?? `Draft #${invoice.id}`}</Link> · <span className="capitalize">{invoice.status}</span></p>)}{documents.invoices.length === 0 && <p className="text-sm text-slate-500">No invoice document.</p>}</div><div className="rounded-lg border p-5"><h3 className="mb-3 font-semibold">Delivery notes</h3>{documents.deliveryNotes.map((note) => <p key={note.id}><Link href={`/delivery-notes/${note.id}`} className="underline">{note.delivery_note_number ?? `Draft #${note.id}`}</Link> · <span className="capitalize">{note.status}</span></p>)}{documents.deliveryNotes.length === 0 && <p className="text-sm text-slate-500">No delivery document.</p>}</div></section>
        {can.recordPayment && order.status === 'confirmed' && paymentSummary.remaining !== '0.0000' && <form onSubmit={recordPayments} className="mb-8 space-y-4 rounded-lg border p-5"><div><h3 className="font-semibold">Record payment</h3><p className="text-sm text-slate-500">Split the remaining balance across one or more methods. The server validates the final total and account compatibility.</p></div>{paymentForm.data.payments.map((entry, index) => <div key={index} className="grid gap-3 rounded bg-slate-50 p-4 md:grid-cols-6"><label className="text-sm">Method<select value={entry.method} onChange={(e) => setEntry(index, 'method', e.target.value)} className="mt-1 w-full rounded border px-3 py-2"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="cheque">Cheque</option></select></label><label className="text-sm md:col-span-2">Financial account<select required value={entry.financial_account_id} onChange={(e) => setEntry(index, 'financial_account_id', e.target.value)} className="mt-1 w-full rounded border px-3 py-2"><option value="">Select account</option>{financialAccounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name} ({account.type.replaceAll('_', ' ')})</option>)}</select></label><label className="text-sm">Amount<input required inputMode="decimal" value={entry.amount} onChange={(e) => setEntry(index, 'amount', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm">Payment date<input required type="date" readOnly={!can.backdatePayment} value={entry.payment_date} onChange={(e) => setEntry(index, 'payment_date', e.target.value)} className="mt-1 w-full rounded border px-3 py-2 read-only:bg-slate-100" /></label><label className="text-sm">Reference<input maxLength={255} value={entry.reference} onChange={(e) => setEntry(index, 'reference', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label><label className="text-sm md:col-span-3">Notes<textarea maxLength={5000} value={entry.notes} onChange={(e) => setEntry(index, 'notes', e.target.value)} className="mt-1 w-full rounded border px-3 py-2" /></label>{paymentForm.data.payments.length > 1 && <button type="button" onClick={() => paymentForm.setData('payments', paymentForm.data.payments.filter((_, position) => position !== index))} className="text-left text-sm text-red-700">Remove split</button>}</div>)}
            {Object.values(paymentForm.errors).map((error) => error && <p key={error} className="text-sm text-red-600">{error}</p>)}<div className="flex gap-2"><button type="button" onClick={() => paymentForm.setData('payments', [...paymentForm.data.payments, blankPayment()])} className="rounded border px-4 py-2">Add split</button><button disabled={paymentForm.processing || financialAccounts.length === 0} className="rounded bg-slate-900 px-4 py-2 text-white disabled:opacity-50">Record payments</button></div>{financialAccounts.length === 0 && <p className="text-sm text-amber-700">Create a compatible active financial account before recording a payment.</p>}</form>}
        {can.cancel && order.status !== 'cancelled' && order.fulfillment_status === 'unfulfilled' && <form onSubmit={cancel} className="max-w-xl space-y-3 rounded-lg border border-red-200 p-5"><h3 className="font-semibold text-red-800">Cancel order</h3><textarea required={order.status === 'confirmed'} value={cancellation.data.reason} onChange={(e) => cancellation.setData('reason', e.target.value)} placeholder={order.status === 'confirmed' ? 'Cancellation reason required' : 'Reason (optional for draft)'} className="w-full rounded border px-3 py-2" /><button className="rounded border border-red-300 px-4 py-2 text-red-800">Cancel order</button></form>}
    </SalesLayout>;
}
